src/Mocks/MockHttpService/Models/ProviderServiceRequest.php

Hi,
From my experience using the library, if the query is not returned in the jsonSerialize result, then it won't be persisted in the pact file generated.
Please disregard the change if it makes no sense to you.

Add query to ProviderServiceRequest model class when json is serialized

---

src/Mocks/MockHttpService/Mappers/ProviderServiceRequestMapper.php
src/Mocks/MockHttpService/Mappers/ProviderServiceResponseMapper.php
src/Mocks/MockHttpService/Models/IHttpMessage.php
src/Mocks/MockHttpService/Models/ProviderServiceRequest.php
src/Mocks/MockHttpService/Models/ProviderServiceResponse.php

Reverts pact-foundation/pact-php#9
This breaks Specification 1.1 : body\empty body no content type.json on https://ci.appveyor.com/project/mattermack/pact-php/build/1.1.46
See:
- https://github.com/pact-foundation/pact-specification/blob/version-1.1/testcases/request/body/empty%20body.json
- https://github.com/pact-foundation/pact-specification/blob/version-1.1/testcases/response/body/empty%20body.json

Revert "Always return headers as array"

---

.gitignore
.php_cs
src/PhpPact/Standalone/Exception/MissingEnvVariableException.php
src/PhpPact/Standalone/Installer/InstallManager.php
src/PhpPact/Standalone/MockService/MockServerConfig.php
src/PhpPact/Standalone/MockService/MockServerConfigInterface.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php

1. Fixed an issue where pact_dir was defaulting to "". This was causing it to default to the root directory "/" which is restricted in Travis CI.
2. Moved the install directory of the Pact binaries to the root of the project. This should make it easier to visualize where it is located and also allow for it to be uninstalled with PACT.

Fixed some issues with default pact dir and required envs

---

src/PhpPact/Broker/Service/BrokerHttpClient.php

I get deprecation warnings after uploading pacts to pact broker (after successull test execution).
Adding leading slashes like in this PR will solve this problem. 
see https://github.com/guzzle/psr7/blob/master/src/Uri.php#L693 
Remaining deprecation notices (1)
1x: The path of a URI with an authority must start with a slash "/" or be empty. Automagically fixing the URI by adding a leading slash to the path is deprecated since version 1.4 and will throw an exception instead.
1x in PactTestListener::endTestSuite from PhpPact\Consumer\Listener
In my project that leads on ci to a non-zero exit code of my script

Fix deprecation warning in GuzzleHttp\Psr7\Uri by adding leading slashes

---

example/tests/Consumer/Service/ConsumerServiceGoodbyeTest.php
src/PhpPact/Consumer/Listener/PactTestListener.php
src/PhpPact/Standalone/Exception/HealthCheckFailedException.php
src/PhpPact/Standalone/Exception/MissingEnvVariableException.php
src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
tests/PhpPact/Consumer/InteractionBuilderTest.php
tests/PhpPact/Standalone/MockServer/MockServerTest.php
tests/PhpPact/Standalone/MockServer/Service/MockServerHttpServiceTest.php

The current namespace for the Exceptions doesn't reflect the directory structure.
This leads to "Class not found" Exceptions. This PR fixes this.

Fix Exception Namespace

---

.travis.yml
composer.json

To verify that pact-php works also with minimal declared dependencies (which appeared it's not).
Original intention was to lower `symfony/*` dependencies to be able to use in symfony 2.x projects. But after that I've realised that dependencies should be not lowered but bumped up :-/.
If I can contribute PR for support of symfony 2.x (yay, we have some legacy here) will it have chances to be accepted?

test also lowest available dependencies

---

composer.json
src/PhpPact/Standalone/Installer/InstallManager.php

After a `composer update` pact-php did not updates the pact binaries. This is related to #64 .
The fix will uninstall pact standalone after an composer update.

Fixed pact bin version mismatch after composer update.

---

README.md
phpunit.xml
src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/MockService/MockServerConfig.php
src/PhpPact/Standalone/MockService/MockServerConfigInterface.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
tests/PhpPact/Standalone/MockServer/MockServerConfigTest.php
tests/PhpPact/Standalone/MockServer/Service/MockServerHttpServiceTest.php

Enables the support of the header `Access-Control-Allow-Origin` setting.

Added cors header support to the MockService.

---

composer.json
src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/Runner/ProcessRunner.php
src/PhpPact/Standalone/StubService/StubServer.php

Depends on #68 
In the end it was about replacing `Process` with `ProcessBuilder`. Other than that works smoothly.
WIP until #68 is merged and I have settled out proper travis setup for symfony 2.x/3.x/4.x components

symfony backward compatibility support

---

composer.json

Another step towards symfony 2.x support. `php-cs-fixer` has dependencies on symfony 3.x . By using phar instead dependencies are not being leaked to the overall library. This PR includes [tm/tooly-composer-script](https://github.com/tommy-muehle/tooly-composer-script) which actually just installs the same phar in the end of the composer command.
I've also updated composer scripts to use local phpunit and php-cs-fixer instead of global one
PS It looks like `composer fix` haven't been run for a while, but I leave it up to maintainers to define/revisit CS rules and CI pipeline for it

use phar distribution of php-cs-fixer

---

composer.json

Follow up from https://github.com/pact-foundation/pact-php/pull/69#issuecomment-387530001 
Enables installing symfony 4.x components in CI as well

do not override current php platform

---

composer.json

Since symfony/console uses [semver](https://semver.org/), it's best to use the composer `^` operator instead of strict upper bounds on version.
This allows this library to play nice with other libraries requiring symfony/console versions 4.1 and 4.2
See:
https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

Loosen symfony/console version bounds

---

example/phpunit.consumer.xml
src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/MockService/MockServerConfig.php
src/PhpPact/Standalone/MockService/MockServerConfigInterface.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
tests/PhpPact/Standalone/MockServer/MockServerTest.php

In my local setup I am not able to start the MockServer within 10 retries/seconds. It takes about 12-14 seconds.
After I patch the allowed timeout in the health check directly everything works as expected.
For better stability I want to define this timeout on my own. Other ppl out there probably too.
Therefore I introduced the env var `PACT_MOCK_SERVER_HEALTH_CHECK_TIMEOUT`. When this env var is not set the timeout the used timeout of 10 retries/seconds is used.

make health check timeout of mock server configurable

---

src/PhpPact/Broker/Service/BrokerHttpClient.php
src/PhpPact/Standalone/ProviderVerifier/Verifier.php
src/PhpPact/Standalone/ProviderVerifier/VerifierProcess.php
tests/PhpPact/Broker/Service/BrokerHttpClientTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

This fixes the confirmed bug in https://github.com/pact-foundation/pact-php/issues/92.
It was not possible to fetch the existing pacts from the broker. [`Verifier::verifyAll`](https://github.com/pact-foundation/pact-php/blob/master/src/PhpPact/Standalone/ProviderVerifier/Verifier.php#L157) assigned always the provider version to the request for fetching the pacts. As a provider version might not exist on the broker yet this resulted in 404 in some cases.
However the provider version should only be used for the publishing process after the verification process.
Example:
```
/pacts/provider/{provider}/1.0.0
/pacts/provider/{provider}/latest
```
As I didn't want to introduce any BC break for this simple change I didn't remove the unneeded second argument in …

Fix broker request when all consumer urls should be fetched

---

src/PhpPact/Consumer/Model/Interaction.php

Not setting the providerState should be valid and that means the `getProviderState()` signature needs to change.
If not set, the providerState property will be omitted from the interaction as expected.
In my case there are a lot of cases where no provider state is needed (and not provided) - the service is written in Java and there is no requirement to have a `@State` annotation in order to run provider tests...

Allow null providerState

---

composer.json
docker-compose.yml
example/README.md
example/phpunit.all.xml
example/phpunit.consumer.xml
example/phpunit.message.consumer.xml
example/phpunit.message.provider.xml
example/phpunit.provider.xml
example/src/Consumer/publish_json_example.php
phpunit.xml

Currently it is not possible to install this library within a new Symfony 4 application (>= 4.1!). This has huge impact on the acceptance for this library in our company.
Besides I see no reason why the Symfony 4 components should be pinned to only < 4.0 and therefore I loose the requirements [once more](https://github.com/pact-foundation/pact-php/commit/527184daab0404a9380e2a277c5b08ae83795be4#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780).
All upcoming Symfony 4.* versions are installable now.
I run the integration tests in the `examples` directory to check if something broke, but everything looks good.
In addition I moved the pact-broker to port `:8080` as port `:80` is often already in use on a host machine.

make latest Symfony 4 components installable

---

src/PhpPact/Consumer/Listener/PactTestListener.php

Defines a env-variable (`PACT_BROKER_SSL_VERIFY`) that allows to disable SSL-verification .
It solves #103

configurable ssl configuration for broker

---

src/PhpPact/Consumer/Listener/PactTestListener.php

While trying to integrate Pact consumer tests into my existing CI, I couldn't get HTTP auth working with the Pact Broker.
Seems like a typo and a quick fix to me

Fix Broker HTTP Authentication

---

example/src/Provider/public/index.php
example/tests/Consumer/Service/ConsumerServiceGoodbyeTest.php
example/tests/Consumer/Service/ConsumerServiceHelloTest.php
src/PhpPact/Standalone/ProviderVerifier/VerifierProcess.php
src/PhpPact/Standalone/Runner/ProcessRunner.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
tests/PhpPact/Standalone/ProviderVerifier/verifier.bat
tests/PhpPact/Standalone/ProviderVerifier/verifier.sh
tests/PhpPact/Standalone/Runner/ProcessRunnerTest.php
tests/PhpPact/Standalone/Runner/verifier.bat
tests/PhpPact/Standalone/Runner/verifier.sh

This pull request ensures that all output is captured, if `VerifierProcess:run()` executes any command that fails (exit code >0)
There are two problems currently:
1. The output is not passed to the logger, if `$processRunner->runBlocking()` throws an exception
2. `ProcessRunner:run()` does not capture the complete output, if stdout and stderr are used alternating (see verifier.sh script in UnitTest)

Verifier output

---

composer.json

In composer.json, the composer/semver package was locked to version 1.4.2, which disallow current v1.5 for that package.

Allow future releases of composer/semver package

---

src/PhpPact/Standalone/Runner/ProcessRunner.php

simplifies ProcessRunner:stop in order to make it work properly on windows systems
fixes #124

Fix windows tests

---

src/PhpPact/Standalone/ProviderVerifier/ProcessRunnerFactory.php
src/PhpPact/Standalone/ProviderVerifier/VerifierProcess.php
src/PhpPact/Standalone/Runner/ProcessRunner.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierProcessTest.php

Fixes https://github.com/pact-foundation/pact-php/issues/135.
The logger methods used during the verification are not included in the standardized LoggerInterface. These methods (addInfo, addError) are contained in Monolith v1 but not in Monolog v2. Thus the verification will break in any fresh installed Symfony 4.3 project.
I changed the usage of the logger to use the interface. It is always a bad practice to rely on concrete classes.
I also introduced ProcessRunnerFactory for better unit testing possibilities.

fix logging during verification

---

phpunit.xml
src/PhpPact/Broker/Service/BrokerHttpClient.php
src/PhpPact/Broker/Service/BrokerHttpClientInterface.php
src/PhpPact/Consumer/Listener/PactTestListener.php

This PR adds bearer token authentication option in BrokerHttpClient(as used in service https://pactflow.io for example).

Add bearer token authentication

---

src/PhpPact/Consumer/Hook/ContractDownloader.php

We are not able to use an included pact-mock server in our CI pipeline (our php images are based on php alpine) due to the following issues:
- https://github.com/pact-foundation/pact-mock-service-npm/issues/18
- https://github.com/pact-foundation/pact-js/issues/305
In order to overcome this problem, we use a separate standalone pact-mock server. Unfortunately, the existing Consumer\Listener\PactTestListener is not designed to fetch the contract from the pact-mock server. I created this PHPUnit hook to fetch and store contract in the configured location, so that the file can be used as an artifact.

Download contract from pact mock server hook

---

src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

Currently custom provider headers are not being enclosed in quotes when passed to `pact-provider-verifier`.
For example, setting: `--custom-provider-header=Authorization: Bearer MyToken`, causes the header to be cut at the first space resulting in the `Authorization` header to have an empty value when parsed by `pact-provider-verifier`.

Fix custom provider headers enclosing

---

README.md

Add missing language indication within the `pact-stub-service` example.

Indicate language to enable syntax highlighting

---

src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php
src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php
src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

Some brokers require the use of a broker token. This adds the ability for a user to set their broker token for verification.

feat: Allow broker token to be set

---

src/PhpPact/Consumer/Model/Message.php

From MessageBuilder:
https://github.com/pact-foundation/pact-php/blob/205ce457b2359386381c6c5326a95e6eaaddbd00/src/PhpPact/Consumer/MessageBuilder.php#L63-L65

Fixed method signature in Model\Message::setProviderState

---

.github/workflows/build.yml
composer.json
src/PhpPact/Consumer/Hook/ContractDownloader.php
src/PhpPact/Consumer/Listener/PactTestListener.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/MessageBuilder.php
src/PhpPact/Consumer/Model/Message.php
src/PhpPact/Standalone/Installer/InstallManager.php
src/PhpPact/Standalone/Installer/Service/InstallerLinux.php
src/PhpPact/Standalone/Installer/Service/InstallerMac.php
src/PhpPact/Standalone/Installer/Service/InstallerWindows.php
src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/MockService/MockServerConfig.php
src/PhpPact/Standalone/MockService/MockServerConfigInterface.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
src/PhpPact/Standalone/PactConfigInterface.php
src/PhpPact/Standalone/PactMessage/PactMessageConfig.php
src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php
src/PhpPact/Standalone/ProviderVerifier/Verifier.php
src/PhpPact/Standalone/StubService/StubServer.php

- add phpstan checks in the pipeline, level 5
- add phpunit to `require` so we can validate version (issue #193)
* set minimum required phpunit version to 8.2.3 (https://github.com/sebastianbergmann/phpunit/issues/3728)
- fix static analysis issues
- extends and contains PR https://github.com/pact-foundation/pact-php/pull/192

Add phpstan for static analysis

---

.github/workflows/build.yml
src/PhpPact/Consumer/Model/ConsumerRequest.php
src/PhpPact/Consumer/Model/ProviderResponse.php
src/PhpPact/Standalone/MockService/MockServer.php

The `string` was to strict and prevented the headers from being matchable.
With this fix you can use matcher in headers like this:
```php
$request = new ConsumerRequest()
->setMethod('POST')
->setPath('/api/call')
->addHeader('Content-Type', 'application/json')
->addHeader('X-Auth-Token', $matcher->like('auth-token'));
```

feat: Support matchers in headers

---

src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

This PR fixes `InvalidArgumentException` exception (with message 'The path of a URI with an authority must start with a slash "/" or be empty') during provider verification from pact broker.
E.g. `(new \GuzzleHttp\Psr7\Uri)->withPath('foo/bar')` throws an exception because the path of a URI with an authority must start with a slash "/" or be empty (See [change log](https://github.com/guzzle/psr7/blob/master/CHANGELOG.md#changed-5)).
Fixes #207

fix: GuzzleHttp\Psr7\Uri invalid path modification

---

src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

As reported yesterday in https://github.com/pact-foundation/pact-php/issues/218, but now with a fix :-).
Here's the original reported issue text:
> Hi,
> 
> First off, thanks for providing and maintaining this package. We are getting much use out of it.
> 
> Unfortunately, when switching to PHP 8.0 (and therefor pact-php 7.1.0), we found that having a whitespace in the provider name (or more specifically, in the value that is used in the --provider= command line argument) breaks our Pact run. That's because on this line: https://github.com/pact-foundation/pact-php/blame/7.1.0/src/PhpPact/Standalone/ProviderVerifier/Verifier.php#L66, the value is not quoted before putting it into the argument list. Another value, for example this one: …

fix: Allow whitespace in the provider name

---

src/PhpPact/Consumer/Model/ConsumerRequest.php
src/PhpPact/Consumer/Model/Interaction.php
src/PhpPact/Consumer/Model/Message.php
src/PhpPact/Consumer/Model/ProviderResponse.php
src/PhpPact/Standalone/MockService/MockServerConfig.php
src/PhpPact/Standalone/ProviderVerifier/Model/ConsumerVersionSelectors.php

Most of them were related to the change of type of PHP Core interfaces, and to maintain compatibility with PHP 7.3, the attribute `#[\ReturnTypeWillChange]` is used, which before PHP 8.0 is interpreted as a comment.
Another change is related with a deprecation when passing `null` in the 3rd argument of `str_replace`.

fix: Address PHP 8.1 deprecations

---

src/PhpPact/Standalone/Installer/InstallManager.php
src/PhpPact/Standalone/Installer/Service/InstallerPosixPreinstalled.php

Its necessary to use a different ruby vendor for arm64 architectures, so this gives the ability to use gem packages pre-installed on a system ruby, such as docker `linux/arm64` images when `linux/amd64` emulation is too unstable

feat: Add installer for system pact binaries if preinstalled on posix systems

---

src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

Especially important for us is the support of the +/-hhmm format  (e.g. `2015-08-06T16:53:10.123+0100`) as it's used in our Java services.

feat: Support all variations of ISO 8601 time zone designators

---

README.md
example/tests/Provider/PactVerifyTest.php
src/PhpPact/Standalone/Installer/Service/InstallerLinux.php
src/PhpPact/Standalone/Installer/Service/InstallerMac.php
src/PhpPact/Standalone/Installer/Service/InstallerWindows.php
src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php
src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php
src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

The Pact Broker now supports branches as first class entities. You can read more about this here: https://github.com/pact-foundation/docs.pact.io/blob/feat/deployments-and-releases/website/blog/2021-07-04-why-we-are-getting-rid-of-tags.md
Closes #223

feat: Add support for publishing verification results with a branch

---

src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

With this change it's possible to fetch pacts directly from broker.

feat: pass pact-broker-base-url argument to verifier process

---

src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

closes #271 
I've also change the `--verbose` argument to `--verbose=VERBOSE`

fix: provider-verifier bad arguments naming

---

composer.json

It has been locked to v1.4.0 in
0aafa78ed78b7e05597e9bba9cc9aad415352def, without an explanation and probably by mistake.

Unlock amphp/cache

---

composer.json
src/PhpPact/Exception/ConnectionException.php
src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/MockService/Service/MockServerHttpService.php
tests/PhpPact/Consumer/InteractionBuilderTest.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php
tests/PhpPact/Consumer/Model/ConsumerRequestTest.php
tests/PhpPact/Consumer/Model/ProviderResponseTest.php
tests/PhpPact/Standalone/Broker/BrokerConfigTest.php
tests/PhpPact/Standalone/Broker/BrokerTest.php
tests/PhpPact/Standalone/MockServer/MockServerConfigTest.php
tests/PhpPact/Standalone/MockServer/MockServerTest.php
tests/PhpPact/Standalone/MockServer/Service/MockServerHttpServiceTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
tests/PhpPact/Standalone/Runner/ProcessRunnerTest.php
tests/PhpPact/Standalone/StubServer/Service/StubServerHttpServiceTest.php
tests/PhpPact/Standalone/StubServer/StubServerConfigTest.php
tests/PhpPact/Standalone/StubServer/StubServerTest.php

* Update phpstan/phpstan to actual version to resolve tons of deprecation warnings.
* specify phpunit versions to avoid install phpunit 10, since they removed some stuff and pact-php not working with it.
* Fix tests namespace to match psr-4 autoloader and avoid additional warnings.

feat: update phpstan/phpstan analyze tool

---

src/PhpPact/Standalone/Broker/Broker.php
tests/PhpPact/Standalone/Broker/BrokerTest.php

In reference to https://github.com/pact-foundation/pact-php/pull/304 
Config class end-user should not be aware of correct passing data with them usage in mind (e.g. quotes).
I think `PhpPact\Standalone\Broker\Broker` class should get correct use of config data and pass them to CLI command in right way.

broker: Fix broker describe pacticipant argument passing

---

src/PhpPact/Standalone/StubService/Service/StubServerHttpService.php
tests/PhpPact/Standalone/StubServer/Service/StubServerHttpServiceTest.php

I saw we have the code but doesn't have the test for it. I wrote it so I verify that this feature did exist

Test stub server health check

---

.github/workflows/build.yml

PHP-CS-FIXER released version 3.15 with PHP 8.2 support

Run php cs fixer on PHP 8.2

---

src/PhpPact/Standalone/MockService/MockServer.php
src/PhpPact/Standalone/MockService/MockServerConfig.php
src/PhpPact/Standalone/MockService/MockServerConfigInterface.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
src/PhpPact/Standalone/PactMessage/PactMessage.php
tests/PhpPact/Standalone/MockServer/MockServerConfigTest.php

continuation of @slt's changes in #316 and #315 with appropriate commit messages.

MockServerConfig defaults and pact-php speed enhancements

---

example/tests/Provider/PactVerifyTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

Attempt to fix the timeout error like this:
```
There was 1 error:
1) PhpPactTest\Standalone\ProviderVerifier\VerifierTest::testVerify
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "php -S 127.0.0.1:7202 -t "D:\a\pact-php\pact-php\tests\PhpPact\Standalone\ProviderVerifier/../../../_public/"" exceeded the timeout of 60 seconds.
D:\a\pact-php\pact-php\vendor\symfony\process\Process.php:1263
D:\a\pact-php\pact-php\vendor\symfony\process\Process.php:468
D:\a\pact-php\pact-php\tests\PhpPact\Standalone\ProviderVerifier\VerifierTest.php:25
```
Link to [failed job](https://github.com/pact-foundation/pact-php/actions/runs/5694624383/job/15436171774?pr=327)

chore: Closing socket connection after opening it

---

example/src/MessageProvider/send.php
example/tests/MessageConsumer/ExampleMessageConsumerTest.php
example/tests/MessageProvider/ExampleMessageProviderTest.php

Fixes cslint errors seen in #336

chore: cslint fixes

---

.github/workflows/build.yml

The error I am trying to fix is:
```
[Fri Sep 22 04:21:58 2023] 127.0.0.1:65468 [500]: POST /pact-change-state - Uncaught UnexpectedValueException: JIT on Windows is not currently supported in D:\a\pact-php\pact-php\vendor\phpseclib\phpseclib\phpseclib\bootstrap.php:28
```
You need this [PR](https://github.com/pact-foundation/pact-php/pull/339) to see the error clearly.
* phpseclib doesn't support [JIT on Windows](https://github.com/phpseclib/phpseclib/blob/master/phpseclib/bootstrap.php#L17), so I need to disable it.
* I tried to set env `PHPSECLIB_ALLOW_JIT` but it seems does not work

Disable jit on windows

---

src/PhpPact/Consumer/Model/Interaction/StatusTrait.php

Fix `Fatal error: Typed property PhpPact\Consumer\Model\ProviderResponse::$status must not be accessed before initialization (Behat\Testwork\Call\Exception\FatalThrowableError)`
* This is mainly for compatibility suite
* For end-user, this change will save them a line of code:
```php
$request = new ConsumerRequest();
$request
->setMethod('GET')
->setPath('/goodbye/Bob')
->addHeader('Content-Type', 'application/json');
$response = new ProviderResponse(); // still need to define an object like this, but it's future improvement, not right now
// $response->setStatus(200); // no need to do this
$config = new MockServerConfig();
$config
->setConsumer('jsonConsumer')
->setProvider('jsonProvider')
->setPactDir(__DIR__.'/../../../pacts');
$builder = new InteractionBuilder($config);
$builder …
```

fix: Fix fatal error when reponse's status is not set

---

example/xml/consumer/tests/Service/HttpClientServiceTest.php
example/xml/provider/tests/PactVerifyTest.php
phpunit.xml

Depend on https://github.com/pact-foundation/pact-php/pull/351, please review it first

Reuse code

---

composer.json
example/matchers/consumer/phpunit.xml
example/matchers/consumer/src/Service/HttpClientService.php
example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/phpunit.xml
example/matchers/provider/public/index.php
example/matchers/provider/tests/PactVerifyTest.php
phpunit.xml
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

The condition `$value !== null` probably related to Ruby core. I tested with `null` value and it works fine. So I remove this condition.
Depend on https://github.com/pact-foundation/pact-php/pull/349, please review it first

Allow like null

---

example/matchers/consumer/tests/Service/MatchersTest.php
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

* On consumer: the example value become `null`
* On provider: because example value become `null`, we got this error on verification:
```
Failures:
1) Verifying a pact between matchersConsumer and matchersProvider Given Get Matchers - A get request to /matchers
1.1) has a matching body
$.arrayContaining -> Expected [102.3,"eb375cad-48cc-4f7f-981b-ea4f1af90bf2"] (Array) to be equal to null (Null)
```

fix: arrayContains matcher doesn't work if variants is array with keys

---

example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

* On consumer: example values will be array with keys:
```
'values' => Array (
-        0 => 'a'
-        1 => 'bb'
-        2 => 'ccc'
+        'a' => 'a'
+        'b' => 'bb'
+        'c' => 'ccc'
)
```
* On provider: got this error on verification:
```
Failures:
1) Verifying a pact between matchersConsumer and matchersProvider Given Get Matchers - A get request to /matchers
1.1) has a matching body
$.values -> Type mismatch: Expected ["a","bb","ccc"] (Array) to be the same type as {"a":"a","b":"bb","c":"ccc"} (Object)
```

fix: values matcher doesn't work if values is array with keys

---

example/matchers/consumer/src/Service/HttpClientService.php
example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

This feature allow to use `regex` matcher to match multiple values for query parameter and header. See https://github.com/pact-foundation/pact-reference/issues/332
This feature is mostly for **compatibility suite**, in [v2/http_consumer](https://github.com/pact-foundation/pact-compatibility-suite/blob/main/features/V2/http_consumer.feature) feature, with these scenarios:
* Supports matchers for repeated request query parameters (positive case)
* Supports matchers for repeated request query parameters (negative case)

feat: allow multi values for regex matcher

---

example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

Revert https://github.com/pact-foundation/pact-php/pull/356
I was wrong #356 is a feature, not a bug.
* When you pass array without keys to `values` matcher, it compare values using its index (i.e. starting with 0) in the array.
* When you pass array with keys to `values` matcher, it compare values using those keys.
* Missing keys/indexes are OK.
* Additional keys/indexes are NOT OK.
* I'm not sure about this behavior.
* Pact complain that the value of additional keys/indexes must equals to the first value (e.g. `a`) ???
* Probably because I'm testing this `values` matcher on `Response`?
* If using this `values` matcher on `Request`, additional keys/indexes are OK. See this behavior on [compatibility suite](https://github.com/pact-foundation/pact-compatibility-suite/blob/main/features/V3/m …

revert: Values matcher accept keys again

---

src/PhpPact/Consumer/Registry/Interaction/Body/AbstractBodyRegistry.php
src/PhpPact/Consumer/Registry/Interaction/Body/MessageContentsRegistry.php

This feature is useful for implementing compatibility suite.

feat: Support inheritance for body

---

example/matchers/consumer/src/Service/HttpClientService.php
example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/Model/Interaction/StatusTrait.php
src/PhpPact/Consumer/Registry/Interaction/Part/ResponseRegistry.php
src/PhpPact/Consumer/Registry/Interaction/Part/ResponseRegistryInterface.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

This matcher can't be used to match the response code unfortunately, because currently `pactffi_response_status` only allow integer status.
But it can be useful to match a value in body (like this example), query parameter or header.

chore: Add status code matcher example

---

composer.json
example/generators/consumer/phpunit.xml
example/generators/consumer/src/Service/HttpClientService.php
example/generators/consumer/tests/Service/GeneratorsTest.php
example/generators/pacts/generatorsConsumer-generatorsProvider.json
example/generators/provider/phpunit.xml
example/generators/provider/public/index.php
example/generators/provider/tests/PactVerifyTest.php
phpunit.xml

There is no example for `MockServerURL`  yet, because the `url` matcher is not available in pact-php (yet)

chore: Add generators example

---

example/binary/consumer/tests/Service/HttpClientServiceTest.php
example/binary/pacts/binaryConsumer-binaryProvider.json
src/PhpPact/Consumer/Exception/BinaryFileNotExistException.php
src/PhpPact/Consumer/Exception/BinaryFileReadException.php
src/PhpPact/Consumer/Model/Body/Binary.php
src/PhpPact/Consumer/Registry/Interaction/Body/AbstractBodyRegistry.php
src/PhpPact/Consumer/Registry/Interaction/Body/MessageContentsRegistry.php
src/PhpPact/FFI/Model/StringData.php

* This is a breaking change, but only inside `10.0.0-alpha.x` versions
* Change c-data from managed to unmanaged

refactor!: Lazy load binary file

---

src/PhpPact/Consumer/Exception/ConsumerException.php
src/PhpPact/Consumer/Matcher/Exception/InvalidUuidFormatException.php
src/PhpPact/Consumer/Matcher/Exception/MatcherException.php
src/PhpPact/Consumer/Matcher/Generators/Uuid.php
src/PhpPact/Exception/BaseException.php
tests/PhpPact/Consumer/Matcher/Generators/UuidTest.php

refactor: Add Uuid generator class

---

src/PhpPact/Consumer/Matcher/Generators/RandomDecimal.php
tests/PhpPact/Consumer/Matcher/Generators/RandomDecimalTest.php

refactor: Add RandomDecimal generator class

---

src/PhpPact/Consumer/Matcher/Generators/MockServerURL.php
tests/PhpPact/Consumer/Matcher/Generators/MockServerURLTest.php

refactor: Add MockServerURL generator class

---

src/PhpPact/Consumer/Matcher/Matchers/Equality.php
src/PhpPact/Consumer/Matcher/Model/MatcherInterface.php
tests/PhpPact/Consumer/Matcher/Matchers/EqualityTest.php

refactor: Add Equality matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/ContentType.php
tests/PhpPact/Consumer/Matcher/Matchers/ContentTypeTest.php

refactor: Add ContentType matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/NotEmpty.php
tests/PhpPact/Consumer/Matcher/Matchers/NotEmptyTest.php

refactor: Add NotEmpty matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/Number.php
tests/PhpPact/Consumer/Matcher/Matchers/NumberTest.php

refactor: Add Number matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/Semver.php
tests/PhpPact/Consumer/Matcher/Matchers/SemverTest.php

refactor: Add Semver matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/StringValue.php
tests/PhpPact/Consumer/Matcher/Matchers/StringValueTest.php

refactor: Add StringValue matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/Type.php
tests/PhpPact/Consumer/Matcher/Matchers/TypeTest.php

refactor: Add Type matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/NullValue.php
tests/PhpPact/Consumer/Matcher/Matchers/NullValueTest.php

refactor: Add NullValue matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/MinType.php
tests/PhpPact/Consumer/Matcher/Matchers/MinTypeTest.php

refactor: Add MinType matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/MaxType.php
tests/PhpPact/Consumer/Matcher/Matchers/MaxTypeTest.php

refactor: Add MaxType matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/Includes.php
tests/PhpPact/Consumer/Matcher/Matchers/IncludesTest.php

refactor: Add Includes matcher class

---

example/generators/consumer/tests/Service/GeneratorsTest.php
example/generators/pacts/generatorsConsumer-generatorsProvider.json
example/generators/provider/public/index.php
example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

* Change the default formats. The previous **default** formats I copied them from https://github.com/pact-foundation/pact-specification/tree/version-4#supported-generators. I think the **new** formats make more sense to end-user.
* Doing so also fixed a failed test: on this specific day `2023-11-30`,  the value become `"2023-12-334T17:15:07"`, not `"2023-11-334T17:15:07"` as expected. I'm not sure what is the problem here.

chore: Change default datetime format

---

src/PhpPact/Consumer/Matcher/Matchers/EachValue.php
tests/PhpPact/Consumer/Matcher/Matchers/EachValueTest.php

Depend on https://github.com/pact-foundation/pact-php/pull/414

refactor: Add EachValue matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/EachKey.php
tests/PhpPact/Consumer/Matcher/Matchers/EachKeyTest.php

Depend on https://github.com/pact-foundation/pact-php/pull/414

refactor: Add EachKey matcher class

---

src/PhpPact/Consumer/Matcher/Matchers/ArrayContains.php
tests/PhpPact/Consumer/Matcher/Matchers/ArrayContainsTest.php

Depend on:
* https://github.com/pact-foundation/pact-php/pull/404
* https://github.com/pact-foundation/pact-php/pull/414

refactor: Add ArrayContains matcher class

---

src/PhpPact/Consumer/Registry/Interaction/MessageRegistry.php
src/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriver.php
src/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverInterface.php
src/PhpPact/SyncMessage/Driver/Pact/AbstractPluginPactDriver.php
src/PhpPact/SyncMessage/Exception/InteractionContentNotAddedException.php
src/PhpPact/SyncMessage/Exception/PluginNotSupportedBySpecificationException.php
src/PhpPact/SyncMessage/Factory/SyncMessageDriverFactory.php
src/PhpPact/SyncMessage/Factory/SyncMessageDriverFactoryInterface.php
src/PhpPact/SyncMessage/Registry/Interaction/Contents/AbstractContentsRegistry.php
src/PhpPact/SyncMessage/Registry/Interaction/SyncMessageRegistry.php
src/PhpPact/SyncMessage/SyncMessageBuilder.php

* This is for implementing compatibility suite
* Code (mostly) taken from this repository https://github.com/tienvx/pact-php-plugin
* In the future I plan to move code from these repositories into this project also:
* https://github.com/tienvx/pact-php-csv
* https://github.com/tienvx/pact-php-protobuf
* https://github.com/tienvx/pact-php-xml
* It means most of the code will be in `pact-php` project. Outside of this project will be framework integration e.g. Symfony:
* https://github.com/tienvx/pact-messenger-bundle
* https://github.com/tienvx/pact-provider-bundle
* No test cases at all. This is because I'm not confident with the code structure yet.

feat: Support sync message

---

src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

I overthought.
There is no breaking changes compare to version <=9. I added `ipv4AddressV3`, `ipv6AddressV3` and `emailV3` in version 10 (alpha)

refactor: Remove unnecessary matchers

---

example/generators/consumer/tests/Service/GeneratorsTest.php
example/generators/pacts/generatorsConsumer-generatorsProvider.json
src/PhpPact/Consumer/Matcher/Exception/MatcherNotSupportedException.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/Model/Interaction/HeadersTrait.php
src/PhpPact/Consumer/Model/Interaction/PathTrait.php
src/PhpPact/Consumer/Model/Interaction/QueryTrait.php
src/PhpPact/Consumer/Model/Interaction/StatusTrait.php
src/PhpPact/Consumer/Model/Message.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php
tests/PhpPact/Consumer/Model/ConsumerRequestTest.php

Depends on https://github.com/pact-foundation/pact-php/pull/373, please review it first

refactor: Use matcher and generator classes

---

src/PhpPact/Consumer/Matcher/Exception/GeneratorNotRequiredException.php
src/PhpPact/Consumer/Matcher/Matchers/GeneratorAwareMatcher.php
tests/PhpPact/Consumer/Matcher/Matchers/BooleanTest.php
tests/PhpPact/Consumer/Matcher/Matchers/DateTest.php
tests/PhpPact/Consumer/Matcher/Matchers/DateTimeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/DecimalTest.php
tests/PhpPact/Consumer/Matcher/Matchers/GeneratorAwareMatcherTestCase.php
tests/PhpPact/Consumer/Matcher/Matchers/IntegerTest.php
tests/PhpPact/Consumer/Matcher/Matchers/NumberTest.php
tests/PhpPact/Consumer/Matcher/Matchers/RegexTest.php
tests/PhpPact/Consumer/Matcher/Matchers/SemverTest.php
tests/PhpPact/Consumer/Matcher/Matchers/StatusCodeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/TimeTest.php

Generator can't be used along with example value:
- Generators (except `ProviderState`) will be silently ignored (without any notice).
- `ProviderState` generator will be used and example value will be ignored (without any notice)
User will be surprised by this.
This PR will throw exception instead.
These code won't be allowed:
- `$this->matcher->fromProviderState($this->matcher->integer(123), '${id}')` (user won't know, until the pact is verified on provider side. And user probably won't notice that `123` is used instead the number from provider)
- `$matchingRule = $this->matcher->integerV3(123); $matchingRule->setGenerator(new RandomInt());` (user probably won't notice that `123` is used instead of a random integer.)

feat: Throw exception when both generator and example value are set

---

example/generators/consumer/tests/Service/GeneratorsTest.php
example/generators/pacts/generatorsConsumer-generatorsProvider.json
example/generators/provider/public/index.php
example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php

This matcher is inspired by `url()` and `url2()` matchers from pact-js
- [Source code](https://github.com/pact-foundation/pact-js/blob/master/src/v3/matchers.ts#L415-L461)
- [Test cases](https://github.com/pact-foundation/pact-js/blob/master/src/v3/matchers.spec.ts#L472-L536)
This PR also confirm my claim from another [PR](https://github.com/pact-foundation/pact-php/pull/420).
> // Temporary fix for inconsistancies between matchers and generators. Matchers use "value" attribute for
// example values, while generators use "example"
I think this is not inconsistent problem, but it's actually a genius idea from Pact core team. We can remove this line from pact-js and it still work fine
```js
if (basePath == null) {
return {
// Remove this line
// value: example,
};
}
```

feat: Add url matcher

---

.gitmodules

[Suggested way](https://github.com/pact-foundation/pact-compatibility-suite#adding-it-to-a-project) of adding compatibility suite is using `git subtree`.
I don't have experience on subtree. I know `git submodule` a bit so I started using it and it sound natural to me. I didn't change since then. The only problem with submodule I got is removing it is a bit complicated.
If subtree is better, please let me know.

test(compatibility-suite): Add compatibility suite submodule

---

composer.json

This script is from version <=9.
In version 10 I refactored the example/ directory.
The public path in the script is not correct any more. And I don't think this script is useful. So I removed it.

chore: Remove old composer script

---

.github/workflows/compatibility-suite.yml
behat.yml
compatibility-suite/suites/v2/http/consumer.yml
compatibility-suite/suites/v2/http/provider.yml
compatibility-suite/tests/Context/V2/Http/ConsumerContext.php
compatibility-suite/tests/ServiceContainer/V2.php

* Implement v2 scenarios (most code implemented from v1). The only different is applying matching rules to request.
* Register `v2/http/consumer` and `v2/http/provider` suites to behat
* Add v2 job to github actions

test(compatibility-suite): Implement V2 scenarios

---

composer.json
example/xml/consumer/tests/Service/HttpClientServiceTest.php
src/PhpPact/Xml/Model/Builder/ElementTrait.php
src/PhpPact/Xml/Model/Builder/GeneratorTrait.php
src/PhpPact/Xml/Model/Builder/MatcherTrait.php
src/PhpPact/Xml/Model/Builder/TextTrait.php
src/PhpPact/Xml/Model/Matcher/Generator.php
src/PhpPact/Xml/Model/Matcher/Matcher.php
src/PhpPact/Xml/XmlBuilder.php
src/PhpPact/Xml/XmlElement.php
src/PhpPact/Xml/XmlText.php
tests/PhpPact/Xml/XmlBuilderIntegrationTest.php
tests/PhpPact/Xml/XmlBuilderTest.php
tests/PhpPact/Xml/XmlElementTest.php
tests/PhpPact/Xml/XmlTextTest.php

* Move code from [xml](https://github.com/tienvx/pact-php-xml) to this repo
* Update code
* Change namespace
* Remove this `(object) ` type casting https://github.com/tienvx/pact-php-xml/blob/main/src/XmlElement.php#L104 to make tests pass. I remember it's just a hack to make tests pass in the original repo.
* Update tests
* Handle new line (`\n` to `\r\n`) on Windows
* Move `Integration/XmlBuilder` to `XmlBuilderIntegrationTest`

refactor: Move xml to core

---

example/generators/consumer/tests/Service/GeneratorsTest.php
src/PhpPact/Consumer/Matcher/Matchers/StringValue.php

I think `RandomString` generator work a bit different from other generators. It work even if the `value` is still there. But it's totally fine. We want this behavior, because:
1. There is no matcher for `string`
2. We need to re-use `type` matcher with a string value
3. That's why `value` must be always a string, even though we are using the `RandomString` generator or not.

chore: Check string generator is working

---

src/PhpPact/Plugins/Protobuf/Driver/Pact/ProtobufPactDriver.php
src/PhpPact/Plugins/Protobuf/Factory/ProtobufMessageDriverFactory.php
src/PhpPact/Plugins/Protobuf/Factory/ProtobufSyncMessageDriverFactory.php
src/PhpPact/Plugins/Protobuf/Registry/Interaction/Body/ProtobufMessageContentsRegistry.php
src/PhpPact/Plugins/Protobuf/Registry/Interaction/ProtobufMessageRegistry.php
src/PhpPact/Plugins/Protobuf/Registry/Interaction/ProtobufSyncMessageRegistry.php
src/PhpPact/Plugins/Protobuf/Service/GrpcMockServer.php

- Move code from [protobuf](https://github.com/tienvx/pact-php-protobuf) to this repo
- Only move the code, there are 2 examples for protobuf and will be in separated PRs
- No tests for these code yet

refactor!: Move protobuf code to core

---

composer.json
example/csv/consumer/phpunit.xml
example/csv/consumer/src/Service/HttpClientService.php
example/csv/consumer/tests/Service/HttpClientServiceTest.php
example/csv/pacts/csvConsumer-csvProvider.json
example/csv/provider/phpunit.xml
example/csv/provider/public/index.php
example/csv/provider/public/report.csv
example/csv/provider/tests/PactVerifyTest.php
phpunit.xml
src/PhpPact/Plugins/Csv/Driver/Pact/CsvPactDriver.php
src/PhpPact/Plugins/Csv/Factory/CsvInteractionDriverFactory.php
src/PhpPact/Plugins/Csv/Registry/Interaction/Body/CsvResponseBodyRegistry.php
src/PhpPact/Plugins/Csv/Registry/Interaction/CsvInteractionRegistry.php

* Move code from [csv](https://github.com/tienvx/pact-php-csv) to this repo
* Update examples
* Cleanup `csv` example
* Fix typo `XmlConsumer` -> `XmlProvider`
Depend on https://github.com/pact-foundation/pact-php/pull/441

refactor!: Move csv to core

---

.cirrus.yml
.cirrus/linux_arm64/Dockerfile

Depend on https://github.com/pact-foundation/pact-php/pull/444
Only apply to linux. The task is now run in `30 seconds` not `30 minutes` (with the same hardware: 2 cores, 4G ram).
Can't apply to macos, because of this error `Intel macOS instances are no longer supported!` https://cirrus-ci.com/task/6049929467002880. I tried [another approach](https://github.com/pact-foundation/pact-php/pull/446) but it doesn't work

ci(test): Compile grpc and cache Linux docker image on Cirrus CI

---

compatibility-suite/tests/Context/V3/Http/ProviderContext.php
composer.json
example/matchers/pacts/matchersConsumer-matchersProvider.json

* Pact core internally change matching rule keys from `$.pages` to `pages`, `$['locales[]']` to `locales[]` in `0.4.12`
* Upgrade to `0.4.13` to fix issue related to `'locales[]` is not supported properly
* `"matchingRules": {"body": []}` now throw an error. It must be ``"matchingRules": {"body": {}}``

deps: Update ffi library to 0.4.13

---

.cirrus.yml
.github/workflows/build.yml
.github/workflows/compatibility-suite.yml

* On local, where everything are set up, it reduce tests running time, from `6.549` seconds to `4.242` (need to set manually `PACT_DO_NOT_TRACK=true phpunit`)
* On github, it's harder to see the difference

ci: Reduce test running time by setting PACT_DO_NOT_TRACK

---

compatibility-suite/tests/Service/GeneratorServer.php
compatibility-suite/tests/Service/ProviderStateServer.php
composer.json
example/binary/provider/tests/PactVerifyTest.php
example/csv/provider/tests/PactVerifyTest.php
example/generators/provider/tests/PactVerifyTest.php
example/json/provider/tests/PactVerifyTest.php
example/matchers/provider/tests/PactVerifyTest.php
example/message/provider/tests/PactVerifyTest.php
example/multipart/provider/tests/PactVerifyTest.php
example/protobuf-async-message/provider/tests/PactVerifyTest.php
example/protobuf-sync-message/provider/tests/PactVerifyTest.php
example/protobuf-sync-message/provider/tests/RoadRunnerProcess.php
example/xml/provider/tests/PactVerifyTest.php
tests/PhpPact/Helper/AbstractProcess.php
tests/PhpPact/Helper/Exception/HelperException.php
tests/PhpPact/Helper/Exception/NoPortAvailableException.php
tests/PhpPact/Helper/PhpProcess.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

* Rename `ProviderProcess` to `AbstractProcess` to reuse code
* Add `PhpProcess`
* Add `RoadRunnerProcess`
* Use dynamic port for `PhpProcess`

chore: Reuse process handling code

---

.github/workflows/build.yml

* `macos-latest` === `macos-12`
* `macos-14` === arm (M1)
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

ci(test): Test mac arm

---

example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/Matcher/Matchers/Values.php

`Values` matcher has weird behaviors. This PR follow the same approach from `pact-js`: `Values` matcher is deprecated in favour of `EachKey` and `EachValue` matchers
See https://github.com/pact-foundation/pact-reference/pull/365

chore: Deprecate Values matcher

---

example/matchers/consumer/src/Service/HttpClientService.php
example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php

* Add example about using matcher on request's header
* Add example about using matcher on response's header
* Add a note about arrayContains, eachKey, eachValue matchers that they are not working with headers

chore: add example for header matchers

---

example/matchers/consumer/tests/Service/MatchersTest.php

* No need to use `array` of matchers
* No need to json encode matcher manually
* Add note about arrayContains, eachKey, eachValue matchers that they are not working with query
* Make note about multi-values query syntax shorter

chore: No need manually json encode matcher

---

src/PhpPact/Standalone/Broker/Broker.php

Added `--output=json` to the arguments of the `canIDeploy` function. Without it it would throw an error every time trying to decode the output of the runner.

add output json flag to can-i-deploy function

---

.github/workflows/build.yml
composer.json

* Upgrade PHP to 8.3
* Drop PHP 8.0
* I was able to compile grpc extension for PHP 8.2 & 8.3 on Windows, so I switch to that file
* Tests on PHP 8.2 and 8.3 on Windows are easier to fail than before with this error `Script phpunit --debug handling the test event returned with error code -1073741819`, I'm not sure why

deps: Upgrade PHP to 8.3 and drop 8.0

---

example/protobuf-sync-message/provider/composer.json

Since PHP has been upgraded to 8.1, `spiral/roadrunner-grpc` can be updated to `^3.2`. This lib is only for testing, so updating isn't a breaking change

deps: Update spiral/roadrunner-grpc

---

example/protobuf-sync-message/provider/composer.json

Update roadrunner binary in the hope of fixing the error `Script phpunit --no-coverage handling the test event returned with error code -1073741819` but it couldn't

deps: Update roadrunner binary

---

src/PhpPact/Consumer/Model/Body/Binary.php
src/PhpPact/Consumer/Registry/Interaction/Body/AbstractBodyRegistry.php
src/PhpPact/Consumer/Registry/Interaction/Body/MessageContentsRegistry.php
src/PhpPact/FFI/Model/BinaryData.php
tests/PhpPact/Consumer/Model/Body/BinaryTest.php

FFI: Change from unmanaged data to managed data
For #371

fix: FFI > Create managed binary data

---

composer.json

Update ffi library to `0.4.16` in the hope of fixing the error `Script phpunit --no-coverage handling the test event returned with error code -1073741819`, but it couldn't

deps: Update ffi library to 0.4.16

---

composer.json

Not sure when or why it's removed. It's still there in my [original code](https://github.com/tienvx/pact-php/blob/rust-ffi/composer.json#L22)

deps: Require ffi extension

---

UPGRADE-10.0.md
src/PhpPact/Standalone/ProviderVerifier/Exception/InvalidSelectorValueException.php
src/PhpPact/Standalone/ProviderVerifier/Exception/ProviderVerifierException.php
src/PhpPact/Standalone/ProviderVerifier/Model/ConsumerVersionSelectors.php
src/PhpPact/Standalone/ProviderVerifier/Model/Selector/Selector.php
src/PhpPact/Standalone/ProviderVerifier/Model/Selector/SelectorInterface.php
tests/PhpPact/Standalone/ProviderVerifier/Model/ConsumerVersionSelectorsTest.php
tests/PhpPact/Standalone/ProviderVerifier/Model/Selector/SelectorTest.php

Instead of asking user to work with json directly, user only need to initiate the object of `Selector` class using PHP 8 named arguments feature. This class help validate and convert selector to json.
Related issue: https://github.com/pact-foundation/pact-php/issues/206
Docs: https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors

feat: Add Selector class

---

src/PhpPact/Consumer/Model/Interaction.php
src/PhpPact/Consumer/Model/Interaction/DescriptionTrait.php
src/PhpPact/Consumer/Model/Message.php

refactor: Move description to trait

---

.github/workflows/build.yml

Try to fix flaky network by using https://github.com/smorimoto/tune-github-hosted-runner-network.
* Hope it help fixing bellow errors (happen mostly on Windows).
* There 2 errors still happen, but I reported [them](https://github.com/pactflow/pact-protobuf-plugin/issues/created_by/tienvx):
* `Script phpunit --no-coverage handling the test event returned with error code -1073741819`
* `ERROR ThreadId(01) pact_ffi::plugins: Could not load plugin - Plugin process did not output the correct startup message in 60 seconds: timed out waiting on channel`
```
Verifying a pact between jsonConsumer and jsonProvider
A get request to /hello/{name} (0s loading, 5s 389ms verification)
Request Failed - error sending request for url (http://localhost:50807/hello/Bob): operation timed out
A get request to …
```

ci: Tune network

---

composer.json
src/PhpPact/Consumer/Driver/Body/InteractionBodyDriver.php
src/PhpPact/Consumer/Driver/Body/InteractionBodyDriverInterface.php
src/PhpPact/Consumer/Driver/Body/MessageBodyDriver.php
src/PhpPact/Consumer/Driver/Body/MessageBodyDriverInterface.php
src/PhpPact/Plugin/Driver/Body/PluginBodyDriver.php
src/PhpPact/Plugin/Driver/Body/PluginBodyDriverInterface.php
src/PhpPact/Plugins/Csv/Driver/Body/CsvBodyDriver.php
src/PhpPact/Plugins/Protobuf/Driver/Body/ProtobufMessageBodyDriver.php
tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php
tests/PhpPact/Consumer/Driver/Body/MessageBodyDriverTest.php
tests/PhpPact/Plugin/Driver/Body/PluginBodyDriverTest.php
tests/PhpPact/Plugins/Csv/Driver/Body/CsvBodyDriverTest.php
tests/PhpPact/Plugins/Protobuf/Driver/Body/ProtobufMessageBodyDriverTest.php

* Remove phpunit 9 (my bad, phpunit is on `require-dev`, so no need to install as many versions as possible. We can remove version 10 as well in the future PR)
* Add body drivers (code taken from body registry)
* Add tests for body drivers
* Use phpunit 10 feature: attributes

refactor: Add body drivers

---

src/PhpPact/Consumer/Driver/InteractionPart/AbstractInteractionPartDriver.php
src/PhpPact/Consumer/Driver/InteractionPart/RequestDriver.php
src/PhpPact/Consumer/Driver/InteractionPart/ResponseDriver.php

* Methods can be call in any order
* Xml's consumer test failed for some reason. We need to check it in core
* That's why, when registering response, `withHeaders` need to be before `withBody` for now

refactor: Remove $this return value

---

.github/workflows/build.yml
.github/workflows/compatibility-suite.yml
composer.json
phpunit.xml

Apply multiple changes to fix **random fails**:
* Update PHPUnit's config file `phpunit.xml`:
* Reduce number of suites
* Change suite's names to make it easier to reference in steps below.
* Default PHP version is used to speed up the jobs. According to this [table](https://github.com/shivammathur/setup-php?tab=readme-ov-file#cloud-osplatform-support):
* Ubuntu: `8.1`
* MacOS 12: `8.2`
* Windows: `8.2`
* MacOS 14 (ARM): currently not supported. Assume `8.2`
* Add `unit` job:
* No need to run on multiple os, only `ubuntu` is enough
* Need to run on multiple php versions `8.1 -> 8.3`
* Need to run on multiple dependency configurations `lowest/locked`
* Can now enable code coverage checking
* Rename `test` job to `examples`
* No need to run on multiple php versions, single version is enough …

ci: Split jobs

---

.github/workflows/build.yml

Reverts pact-foundation/pact-php#488

Revert "ci: Tune network"

---

.github/workflows/compatibility-suite.yml

```
--colors                           Force ANSI color in the output. By default color support is
guessed based on your platform and the output if not specified.
```
Currently it guessed that github actions does not support color. So I have to force it to make it easier to see the results (which step pass, which fail)

ci(compatibility-suite): Force output colors for behat

---

compatibility-suite/suites/v4/message/provider.yml
compatibility-suite/tests/Context/V3/Message/ProviderContext.php
compatibility-suite/tests/Context/V4/CombinedContext.php
compatibility-suite/tests/Context/V4/Http/ConsumerContext.php
compatibility-suite/tests/Context/V4/Message/ConsumerContext.php
compatibility-suite/tests/Context/V4/Message/ProviderContext.php
compatibility-suite/tests/Context/V4/SyncMessage/ConsumerContext.php
compatibility-suite/tests/Service/MessagePactWriter.php
compatibility-suite/tests/Service/MessagePactWriterInterface.php
composer.json
src/PhpPact/Consumer/AbstractMessageBuilder.php
src/PhpPact/Consumer/Driver/Exception/InteractionKeyNotSetException.php
src/PhpPact/Consumer/Driver/Interaction/AbstractDriver.php
src/PhpPact/Consumer/Driver/Interaction/AbstractMessageDriver.php
src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php
src/PhpPact/Consumer/InteractionBuilder.php
src/PhpPact/Consumer/Model/Interaction.php
src/PhpPact/Consumer/Model/Interaction/KeyTrait.php
src/PhpPact/Consumer/Model/Message.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/Consumer/Driver/Pact/PactDriverTest.php
tests/PhpPact/Helper/FFI/ClientTrait.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

* Allow setting interaction/message interaction's key 
* This is for v4, using this feature on <= v3 doesn't have any effect to the pact file
* Update compatibility suite to use this feature
I'm not sure:
* Did other languages implement it for end-user?
* How did other languages implement for end-user?
* Should all languages follow the same naming convention?
So I invented 3 methods in builder:
```php
$config = new MockServerConfig();
$config->setPactSpecificationVersion('4.0.0');
$builder = new InteractionBuilder($config);
$builder
->key('key')
->pending(true) // other PR
->comments(['key' => 'value']) // other PR
->given('Get Goodbye')
->uponReceiving('A get request to /goodbye/{name}')
->with($request)
->willRespondWith($response);
```
Is this okay?
Should I change to `setKey`, …

feat: Allow set interaction key for v4

---

compatibility-suite/tests/Context/V4/Http/ConsumerContext.php
compatibility-suite/tests/Context/V4/Message/ConsumerContext.php
compatibility-suite/tests/Context/V4/SyncMessage/ConsumerContext.php
src/PhpPact/Consumer/AbstractMessageBuilder.php
src/PhpPact/Consumer/Driver/Exception/InteractionPendingNotSetException.php
src/PhpPact/Consumer/Driver/Interaction/AbstractDriver.php
src/PhpPact/Consumer/Driver/Interaction/AbstractMessageDriver.php
src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php
src/PhpPact/Consumer/InteractionBuilder.php
src/PhpPact/Consumer/Model/Interaction.php
src/PhpPact/Consumer/Model/Interaction/PendingTrait.php
src/PhpPact/Consumer/Model/Message.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

- Allow marking interaction/message interaction as pending
- This is for v4, using this feature on <= v3 doesn't have any effect to the pact file
- Update compatibility suite to use this feature
- Add method `pending(bool)` to builders for end-users

feat: Allow mark interaction as pending for v4

---

compatibility-suite/tests/Context/V4/Http/ConsumerContext.php
compatibility-suite/tests/Context/V4/Message/ConsumerContext.php
compatibility-suite/tests/Context/V4/SyncMessage/ConsumerContext.php
src/PhpPact/Consumer/AbstractMessageBuilder.php
src/PhpPact/Consumer/Driver/Exception/InteractionCommentNotSetException.php
src/PhpPact/Consumer/Driver/Interaction/AbstractDriver.php
src/PhpPact/Consumer/Driver/Interaction/AbstractMessageDriver.php
src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php
src/PhpPact/Consumer/InteractionBuilder.php
src/PhpPact/Consumer/Model/Interaction.php
src/PhpPact/Consumer/Model/Interaction/CommentsTrait.php
src/PhpPact/Consumer/Model/Message.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

- Allow adding comments to interaction/message interaction
- This is for v4, using this feature on <= v3 doesn't have any effect to the pact file
- Update compatibility suite to use this feature
- Related PR https://github.com/pact-foundation/pact-compatibility-suite/pull/8
- Add method `comments(array)` to builders for end-users

feat: Allow set comments for interaction in v4

---

.github/workflows/build.yml

* PHP `8.3` replace `8.2` as default version in `macos-12` https://github.com/shivammathur/setup-php/commit/88841d1465a6792bd2428eb9e67f05bfbb15c304
* Time to install PHP reduced from `2m 12s` to `1m 16s`

ci: Update PHP to 8.3 for MacOS 12

---

src/PhpPact/Consumer/Driver/Pact/PactDriver.php
tests/PhpPact/Consumer/Driver/Pact/PactDriverTest.php

Fix `TypeError: PhpPact\Consumer\Driver\Pact\PactDriver::getSpecification(): Return value must be of type int, Closure returned`

fix: Fix unknown specification not working

---

compatibility-suite/tests/Service/PactBroker.php

I think recent update to pact broker `2.115` or `2.116` cause pact broker to hang. Move to `2.114` a month ago solve the issue

test(compatibility-suite): Fix compatibility suite v1 hang

---

src/PhpPact/Consumer/InteractionBuilder.php
tests/PhpPact/Consumer/InteractionBuilderTest.php

* Allow to build multiple interactions
* Convert `InteractionBuilderTest` to unit tests with mocks
This is how end-user use it:
```php
$builder = new InteractionBuilder($config);
$builder
->given('a person exists')
->uponReceiving('a get request to /hello/{name}')
->with($request)
->willRespondWith($response, false);
$builder
->newInteraction()
->given('a person exists')
->uponReceiving('a get request to /goodbye/{name}')
->with($request)
->willRespondWith($response);
```
If not using this feature (nothing change):
```php
$builder = new InteractionBuilder($config);
$builder
->given('a person exists')
->uponReceiving('a get request to /hello/{name}')
->with($request)
->willRespondWith($response);
```

feat: Allow to build multiple interactions

---

example/csv/consumer/tests/Service/HttpClientServiceTest.php
src/PhpPact/Plugins/Csv/Exception/CsvException.php
src/PhpPact/Plugins/Csv/Exception/MissingPluginPartsException.php
src/PhpPact/Plugins/Csv/Factory/CsvInteractionDriverFactory.php
tests/PhpPact/Helper/FactoryTrait.php
tests/PhpPact/Plugins/Csv/Factory/CsvInteractionDriverFactoryTest.php

Currently `CsvInteractionDriverFactory` only support csv in response.
This PR also support csv in request.

feat: Allow sending csv body in request

---

composer.json
src/PhpPact/Consumer/Driver/Body/InteractionBodyDriver.php
src/PhpPact/Consumer/Exception/PartNotExistException.php
src/PhpPact/Consumer/Model/Body/Part.php
tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php

File's path will be validated by core. Here is the error when the file does not exist:
```
PhpPact\Consumer\Exception\PartNotAddedException: Can not add part 'full_name': with_multipart_file: failed to generate multipart body - convert_ptr_to_mime_part_body: Failed to generate multipart body: No such file or directory (os error 2)
```

refactor: Remove file_exists checking

---

example/xml/consumer/tests/Service/HttpClientServiceTest.php
example/xml/pacts/xmlConsumer-xmlProvider.json
example/xml/provider/public/index.php
tests/PhpPact/Xml/XmlBuilderTest.php

* Test mixed content in xml's example
* Test mixed content in unit test
It's supported in core but it's not tested anywhere.
Here is the link I got about xml's mixed content: https://stackoverflow.com/questions/12130228/can-a-xml-element-contain-text-and-child-elements-at-the-same-time

test: Test xml's mixed content

---

tests/PhpPact/Consumer/Model/InteractionTest.php
tests/PhpPact/Consumer/Model/MessageTest.php

The methods `setProviderState(string $name, array $params, bool $overwrite)` and `addProviderState(string $name, array $params, bool $overwrite)` are the same, and they look weird to me.
But I don't change them in order to prevent breaking changes. I only add tests for them.

test: Test add/set provider state for interaction/message

---

composer.json

* `slim/psr7` is in `require-dev` because old version of slim framework need it in the past.
* Look like new version of Slim framework doesn't require `slim/psr7` to work.

deps: Remove slim/psr7

---

composer.json

* Look like `ext-openssl` is required in <= v8 because we call `file_get_contents` with `https` scheme https://github.com/pact-foundation/pact-php/commit/50140a53210fca4ba9363f98f8d68ddf6bd0acb3
```php
$uri  = "https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.29.2/{$fileName}";
$data = \file_get_contents($uri);
```
* v9 + v10 use composer to download files with `https` scheme. Composer will "require" `ext-openssl` for us, by throwing an exception if it's not available https://github.com/composer/composer/blob/main/src/Composer/Downloader/FileDownloader.php#L468-L470
```php
if (!extension_loaded('openssl') && 0 === strpos($url, 'https:')) {
throw new \RuntimeException('You must enable the openssl extension to download files via https');
}
```
* I think not …

deps: Require ext-openssl

---

composer.json

chore: Keep start-provider script but return error

---

composer.json
example/protobuf-sync-message/provider/composer.json

I can't wait for the package `pact-foundation/composer-downloads-plugin` to be submitted into packagist. So I use composer's `repositories` feature for now. We can remove it when the package is submitted.

deps: Use pact-foundation/composer-downloads-plugin

---

README.md

* Spec 1.1 is mentioned starting from version [1.0.1](https://github.com/pact-foundation/pact-php/tree/1.0.1?tab=readme-ov-file#pact-php)
* Spec 2.0 is mentioned starting from version [2.0.1](https://github.com/pact-foundation/pact-php/tree/2.0.1?tab=readme-ov-file#pact-php)
* Spec 3.0 and above: fully supported in version 10

docs: Use table to show supported specifications

---

README.md
docs/SOFTWARE-HISTORY.md

* Merge `#Versions` and `#Specifications` by just adding a single column to the table, making `Readme.md` a lot shorter
* I think most of `updating dependencies and libraries` information can be removed
* `ARM64` support on Linux and Mac is already in the table below `#Supported Platforms`

docs: Add PHP Compatibility column to table

---

src/PhpPact/Consumer/Matcher/Matchers/ArrayContains.php
tests/PhpPact/Consumer/Matcher/Matchers/ArrayContainsTest.php

Look like `value` is required if the `arrayContains` matcher is used with query and header.
Currently I set it exactly the same with `variants` and it works fine.
https://github.com/pact-foundation/pact-specification/tree/version-4?tab=readme-ov-file#supported-matching-rules

feat: Support 'arrayContains' matcher in query and header

---

README.md
docs/ADDITIONAL-EXAMPLES.md

These examples are quite old, for v2.x and v3.x. Current versions are 9.x and 10.x

docs: Move additional examples to docs/

---

compatibility-suite/tests/Context/V4/Http/ConsumerContext.php
compatibility-suite/tests/Context/V4/Message/ConsumerContext.php
compatibility-suite/tests/Context/V4/SyncMessage/ConsumerContext.php
src/PhpPact/Consumer/AbstractMessageBuilder.php
src/PhpPact/Consumer/Driver/Interaction/AbstractDriver.php
src/PhpPact/Consumer/InteractionBuilder.php
src/PhpPact/Consumer/Model/Interaction/CommentsTrait.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/Consumer/InteractionBuilderTest.php
tests/PhpPact/Consumer/MessageBuilderTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php
tests/PhpPact/SyncMessage/SyncMessageBuilderTest.php

`pactffi_set_comment` does work, but there is a problem. `pactffi_add_text_comment` is a better replacement for it.
See these links for more information:
* https://github.com/pact-foundation/pact-compatibility-suite/pull/8
* https://github.com/pact-foundation/pact-specification/issues/45
* https://github.com/pact-foundation/pact-reference/pull/401

chore: Use both pactffi_set_comment and pactffi_add_text_comment

---

README.md

* Reorganize 'provider usage' section in readme
* Update table of contents
* Use recommended consumer version selectors (`deployedOrReleased` and `mainBranch` instead of `tag` and `latest`) https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors#recommended

docs: Reorganize provider usage in readme

---

UPGRADE-10.0.md

Plugin examples were moved to core. Other examples were added.

docs: Update links to examples

---

tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php
tests/PhpPact/Consumer/Driver/Body/MessageBodyDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/Consumer/Driver/InteractionPart/RequestDriverTest.php
tests/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverTest.php
tests/PhpPact/Consumer/Driver/Pact/PactDriverTest.php
tests/PhpPact/Consumer/Factory/InteractionDriverFactoryTest.php
tests/PhpPact/Consumer/Factory/MessageDriverFactoryTest.php
tests/PhpPact/Consumer/InteractionBuilderTest.php
tests/PhpPact/Consumer/MessageBuilderTest.php
tests/PhpPact/Consumer/Service/MockServerTest.php
tests/PhpPact/Helper/FFI/ClientTrait.php
tests/PhpPact/Plugin/Driver/Body/PluginBodyDriverTest.php
tests/PhpPact/Plugins/Csv/Driver/Body/CsvBodyDriverTest.php
tests/PhpPact/Plugins/Csv/Factory/CsvInteractionDriverFactoryTest.php
tests/PhpPact/Plugins/Protobuf/Driver/Body/ProtobufMessageBodyDriverTest.php
tests/PhpPact/Plugins/Protobuf/Factory/ProtobufMessageDriverFactoryTest.php
tests/PhpPact/Plugins/Protobuf/Factory/ProtobufSyncMessageDriverFactoryTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
tests/PhpPact/Standalone/StubServer/StubServerTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php
tests/PhpPact/SyncMessage/Factory/SyncMessageDriverFactoryTest.php
tests/PhpPact/SyncMessage/SyncMessageBuilderTest.php

When running static code analysis on `tests/`, there will be a lot of errors like this:
```
Call to an undefined method PhpPact\SomeInterface|PHPUnit\Framework\MockObject\MockObject::expects().
```
This can be fixed by using `intersection types` instead of `union types`. This is a new feature from PHP 8.1 (lowest supported PHP version by Pact-PHP)
By doing this fix more than 110 errors (out of 218 errors) in https://github.com/pact-foundation/pact-php/pull/564

chore: Use intersection types feature

---

tests/PhpPact/Consumer/Model/ConsumerRequestTest.php
tests/PhpPact/Standalone/ProviderVerifier/Model/Source/BrokerTest.php
tests/PhpPact/Standalone/ProviderVerifier/Model/Source/UrlTest.php
tests/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigTest.php
tests/PhpPact/Standalone/StubServer/StubServerConfigTest.php

This change fix errors like this:
```
Method PhpPactTest\SomeTest::testSomething() has  no return type specified.
```
in https://github.com/pact-foundation/pact-php/pull/564

chore: Add void return type to tests

---

tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

Fix errors like this:
```
Method PhpPactTest\SomeTest::testSomething() has parameter $success with no type specified.
```
in https://github.com/pact-foundation/pact-php/pull/564

chore: Add parameter type

---

tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/MessageBuilderTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

Fix errors like:
```
Parameter #1 $count of method PHPUnit\Framework\TestCase::exactly() expects int, bool given.
```
in https://github.com/pact-foundation/pact-php/pull/564

chore: Fix bool to int casting errors

---

tests/PhpPact/Consumer/Matcher/Matchers/StatusCodeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/StringValueTest.php

```
Parameter #2 $value of class PhpPact\Consumer\Matcher\Matchers\StatusCode constructor expects int|null,
string|null given.
```
```
Parameter #2 $actualJson of method PHPUnit\Framework\Assert::assertJsonStringEqualsJsonString() expects string,  
string|false given.
```

chore: Fix wrong types

---

tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/Consumer/Driver/InteractionPart/RequestDriverTest.php
tests/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverTest.php
tests/PhpPact/Consumer/InteractionBuilderTest.php
tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/ValueOptionalFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/ValueRequiredFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/XmlContentFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/XmlElementFormatterTest.php
tests/PhpPact/Consumer/Matcher/Generators/DateTest.php
tests/PhpPact/Consumer/Matcher/Generators/DateTimeTest.php
tests/PhpPact/Consumer/Matcher/Generators/TimeTest.php
tests/PhpPact/Consumer/Matcher/Generators/UuidTest.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php
tests/PhpPact/Consumer/Matcher/Matchers/GeneratorAwareMatcherTestCase.php
tests/PhpPact/Consumer/Matcher/Matchers/MatchingFieldTest.php
tests/PhpPact/Consumer/Matcher/Matchers/RegexTest.php
tests/PhpPact/Consumer/Matcher/Matchers/ValuesTest.php
tests/PhpPact/Consumer/MessageBuilderTest.php
tests/PhpPact/Helper/FFI/ClientTrait.php
tests/PhpPact/Plugin/Driver/Body/PluginBodyDriverTest.php
tests/PhpPact/Standalone/ProviderVerifier/Model/ConsumerVersionSelectorsTest.php
tests/PhpPact/Standalone/ProviderVerifier/Model/Selector/SelectorTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php
tests/PhpPact/SyncMessage/SyncMessageBuilderTest.php

```
Method PhpPactTest\SomeTest::testSomething() has         
parameter $data with no value type specified in iterable type array.
```
```
Method                                                                                      
PhpPactTest\SomeTest::someProvider()              
return type has no value type specified in iterable type array.
```
```
Property                                                                              
PhpPactTest\SomeTest::$something type         
has no value type specified in iterable type array.
```

chore: Specify type of array

---

tests/PhpPact/Consumer/MessageBuilderTest.php
tests/PhpPact/Helper/FactoryTrait.php
tests/PhpPact/SyncMessage/SyncMessageBuilderTest.php

```
Parameter #1 $expected of method PHPUnit\Framework\Assert::assertInstanceOf()  
expects class-string<object>, string given.
```

chore: Use class-string PHPdoc

---

tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

Fix this error:
```
Variable $key might not be defined.
```

chore: Fix 'Variable $key might not be defined'

---

tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php
tests/PhpPact/Consumer/Driver/InteractionPart/RequestDriverTest.php
tests/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverTest.php

Fix errors like this:
```
Match expression does not handle remaining value: array{string, int, int,  
string, string, string, string}
```
```
Match expression does not handle remaining value: mixed
```

chore: Fix 'Match expression does not handle remaining value'

---

tests/PhpPact/Consumer/MessageBuilderTest.php

```
201    Parameter #1 $callback of method                                                 
PhpPact\Consumer\MessageBuilder::verifyMessage() expects callable(): mixed,      
PHPUnit\Framework\MockObject\MockObject&stdClass given.                          
225    Parameter #1 $callback of method PhpPact\Consumer\MessageBuilder::setCallback()  
expects callable(): mixed, PHPUnit\Framework\MockObject\MockObject&stdClass      
given.
```

chore: Fix variable not callable

---

tests/PhpPact/FFI/Model/BinaryDataTest.php

```
22     Parameter #1 $string of function strlen expects string, string|false given.     
24     Parameter #1 $contents of static method                                         
PhpPact\FFI\Model\BinaryData::createFrom() expects string, string|false given.
```

chore: Assert variable is string

---

src/PhpPact/Standalone/ProviderVerifier/Model/Source/Url.php
src/PhpPact/Standalone/ProviderVerifier/Model/Source/UrlInterface.php

Fix this error:
```
------ --------------------------------------------------------------------------- 
Line   tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php                 
------ --------------------------------------------------------------------------- 
172    Call to an undefined method                                                
PhpPact\Standalone\ProviderVerifier\Model\Source\Url::setEnablePending().  
------ ---------------------------------------------------------------------------
```
It also fix a warning in IDE https://github.com/pact-foundation/pact-php/pull/517

chore: Fix call to undefined method

---

tests/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverTest.php

Fix this error:
```
40     Parameter #1 $status of method                                        
PhpPact\Consumer\Model\ProviderResponse::setStatus() expects          
int|PhpPact\Consumer\Matcher\Model\MatcherInterface, string given.
```

chore: Fix wrong type

---

README.md

Just working on a docs sync job to pact-docs site and this throws an error because there isn't an opening tag

docs(chore): remove erroneous span closing tag

---

.github/workflows/trigger_pact_docs_update.yml

sync job not currently present in docs.pact.io repo on master, but will be later today

docs(ci): add trigger update to docs.pact.io

---

src/PhpPact/Consumer/Matcher/Formatters/PluginFormatter.php
src/PhpPact/Consumer/Matcher/Matchers/NotEmpty.php
tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php
tests/PhpPact/Consumer/Matcher/Matchers/NotEmptyTest.php

There are a lot of `if` conditions in `PluginFormatter`. I think `Visitor` pattern can be applied to solve this.

refactor: Apply Visitor pattern for NotEmpty matcher

---

src/PhpPact/Consumer/Matcher/Formatters/PluginFormatter.php
src/PhpPact/Consumer/Matcher/Matchers/MatchingField.php
tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php

Reverts pact-foundation/pact-php#589

Revert "refactor: Apply Visitor pattern for MatchingField matcher"

---

example/matchers/consumer/tests/Service/MatchersTest.php
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/matchers/provider/public/index.php
src/PhpPact/Consumer/Matcher/Formatters/CombinedMatchersFormatter.php
src/PhpPact/Consumer/Matcher/Formatters/PluginFormatter.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/Matcher/Matchers/CombinedMatchers.php
src/PhpPact/Consumer/Matcher/Matchers/MatchAll.php
src/PhpPact/Consumer/Matcher/Model/CombinedMatchersInterface.php
src/PhpPact/Consumer/Matcher/Trait/MatchersTrait.php
tests/PhpPact/Consumer/Matcher/Formatters/CombinedMatchersFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MatchAllTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MatchingFieldTest.php

Implemented this feature https://github.com/pact-foundation/pact-reference/pull/405

feat: Allow combining matchers

---

compatibility-suite/tests/Service/MatchingRuleConverter.php
example/matchers/consumer/tests/Service/MatchersTest.php
src/PhpPact/Consumer/Matcher/Formatters/Expression/MaxTypeFormatter.php
src/PhpPact/Consumer/Matcher/Formatters/Expression/MinMaxTypeFormatter.php
src/PhpPact/Consumer/Matcher/Formatters/Expression/MinTypeFormatter.php
src/PhpPact/Consumer/Matcher/Formatters/Json/MaxTypeFormatter.php
src/PhpPact/Consumer/Matcher/Formatters/Json/MinMaxTypeFormatter.php
src/PhpPact/Consumer/Matcher/Formatters/Json/MinTypeFormatter.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/Matcher/Matchers/MaxType.php
src/PhpPact/Consumer/Matcher/Matchers/MinMaxType.php
src/PhpPact/Consumer/Matcher/Matchers/MinType.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MatchAllFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MinMaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Json/MatchAllFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Json/MaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Json/MinMaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Json/MinTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MatchAllTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MaxTypeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MinMaxTypeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MinTypeTest.php

* Value for MinType/MaxType/MinMaxType matchers now is not array
* Add expression/json formatters for MinType/MaxType/MinMaxType matchers
* Remove ability to set number of examples. I don't think it's important.
* Pact-JS has this ability
* Pact-GO doesn't have this ability (https://github.com/pact-foundation/pact-go/blob/master/matchers/matcher_v3.go#L190-L193)
* Pact-PHP is mixed . 1 matcher has (`constrainedArrayLike`). others don't
* Now it's just like Pact-GO

refactor: Add formatters for Min/Max Type matchers

---

.github/workflows/build.yml
Dockerfile
README.md
composer.json
example/binary/consumer/tests/Service/HttpClientServiceTest.php
example/multipart/consumer/tests/Service/HttpClientServiceTest.php

Thanks @YOU54F for the implementation. Here is the original code https://github.com/pact-foundation/pact-php/compare/master...YOU54F:pact-php:tx-support-alpine
We will need to update the Alpine ci once Github Actions Linux ARM is available.

feat: Support Alpine

---

Dockerfile

This file come from https://github.com/pact-foundation/pact-php/pull/613, which is no longer needed because of installing packages directly

chore: Remove unused Dockerfile

---

.github/workflows/build.yml

* I'm not sure why setting up PHP 8.1 on Ubuntu 22.04 taking so long, probably because it need to compile grpc extension from source code. I think the default PHP version changed to 8.3, but the [document](https://github.com/shivammathur/setup-php?tab=readme-ov-file#github-hosted-runners) is not updated.
* Solution: Upgrade PHP to 8.3
* Look like grpc extension is available for PHP 8.3 on Windows https://pecl.php.net/package/gRPC
* Change: Upgrade PHP to 8.3 to make tests run faster, since PHP 8.3 is default version on Windows
* There are no default version of PHP installed on macos-14 https://github.com/shivammathur/setup-php?tab=readme-ov-file#github-hosted-runners
* So upgrade PHP from 8.2 to `8.3` doesn't make the tests run slower

ci: Upgrade PHP to 8.3

---

docs/consumer.md
example/json/consumer/tests/Service/ConsumerServiceMultipleInteractionsTest.php
example/json/pacts/jsonConsumer-jsonProvider.json

https://github.com/pact-foundation/pact-php/pull/508 added the support to have multiple independent interactions with one builder, but:
- it was not documented
- the examples in the PR did not work for me (maybe the code got changed since then) :man_shrugging: 
This PR adds documentation for this super useful feature and adds an example

docs: document multiple interactions

---

compatibility-suite/tests/Service/Server.php

Currently running compatibility suites tests doesn't print out any mock server's log messages.  So it's hard to debug failed test like this:
```
Then a 200 success response is returned
Failed asserting that 500 is identical to 200.
```
And there is no way to customize this.
This PR pass the `PACT_LOGLEVEL` env to mock server.  It allow me to run the `behat` command with custom (mock server) debug level:
```shell
env PACT_LOGLEVEL=debug vendor/bin/behat compatibility-suite/pact-compatibility-suite/features/V1/http_consumer.feature:204 --colors
```
Then it will print out useful log messages from mock server like this:
```
...
2024-08-29T05:41:00.882246Z DEBUG tokio-runtime-worker pact_matching: --> Mismatches: [HeaderMismatch { key: "Content-Type", expected: "text/plain", actual: …
```

feat: Allow debug mock server in compatibility suites

---

composer.json
example/binary/pacts/binaryConsumer-binaryProvider.json
example/csv/pacts/csvConsumer-csvProvider.json
example/generators/pacts/generatorsConsumer-generatorsProvider.json
example/matchers/pacts/matchersConsumer-matchersProvider.json
example/message/pacts/messageConsumer-messageProvider.json
example/multipart/pacts/multipartConsumer-multipartProvider.json
example/protobuf-async-message/pacts/protobufAsyncMessageConsumer-protobufAsyncMessageProvider.json
example/protobuf-async-message/provider/public/index.php
example/protobuf-sync-message/pacts/protobufSyncMessageConsumer-protobufSyncMessageProvider.json
example/xml/pacts/xmlConsumer-xmlProvider.json

Fix this error if using protobuf plugin version 0.5 (not sure about 0.4)
```
expected a body of 'application/protobuf;message=.library.Person' but the actual content type was 'application/protobuf;message=Person'
```
I guess the `.library.` and `.plugins.` prefixes come from the `package library;` and `package plugins;` in proto files.
Depend on https://github.com/pact-foundation/pact-php/pull/622

Fix wrong content type in protobuf plugin 0.5

---

composer.json

Updates to [libpact_ffi 0.4.22](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.22)
Introduces failures in content-type detection possibly due to changes introduced in this [PR](https://github.com/pact-foundation/pact-reference/pull/456)

fix: update pact-ffi to 0.4.22

---

example/xml/consumer/tests/Service/HttpClientServiceTest.php
src/PhpPact/Consumer/Driver/InteractionPart/ResponseDriver.php

The reason is:
```php
->setBody(
json_encode($xmlBuilder)
);
```
This code set body's content type to `text/plain`. I need to set the content type to the correct one (`application/xml`)
cc @JP-Ellis 
Link to related issue/comment:
* https://github.com/pact-foundation/pact-php/pull/619
* https://github.com/pact-foundation/pact-reference/pull/456#issuecomment-2240815563

fix: Fix 'Exception: String could not be parsed as XML' in xml's consumer test

---

UPGRADE-10.0.md
compatibility-suite/tests/Service/HttpClient.php
docs/provider.md
src/PhpPact/Consumer/Driver/Interaction/InteractionDriverInterface.php
src/PhpPact/Standalone/ProviderVerifier/Model/Config/CustomHeaders.php
src/PhpPact/Standalone/ProviderVerifier/Model/Config/CustomHeadersInterface.php
src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php
src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php
src/PhpPact/Standalone/ProviderVerifier/Verifier.php
tests/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigTest.php
tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php

Add ability to add custom provider headers to v10. Somehow I didn't notice this feature is available in v9 and FFI at the same time.

feat: Allow add custom provider headers

---

composer.json
example/graphql/consumer/autoload.php
example/graphql/consumer/phpunit.xml
example/graphql/consumer/src/Service/HttpClientService.php
example/graphql/consumer/tests/Service/HttpClientServiceTest.php
example/graphql/pacts/graphqlConsumer-graphqlProvider.json
example/graphql/provider/autoload.php
example/graphql/provider/phpunit.xml
example/graphql/provider/public/index.php
example/graphql/provider/tests/PactVerifyTest.php

Depend on https://github.com/pact-foundation/pact-php/pull/633
Currently we can only test json response. We can't test the query DSL.
I think we can take inspiration from pact-js https://docs.pact.io/implementation_guides/javascript/docs/graphql

feat: Add graphql example

---

composer.json

Depend on https://github.com/pact-foundation/pact-php/pull/633
Look like this issue https://github.com/pact-foundation/pact-php/pull/622 doesn't happen anymore with PHPUnit 11.3.6? I'm not so sure

deps: Allow update to PHPUnit 11.3

---

src/PhpPact/Consumer/Driver/Body/InteractionBodyDriver.php
src/PhpPact/FFI/Client.php
src/PhpPact/FFI/ClientInterface.php
src/PhpPact/FFI/Exception/InvalidEnumException.php
src/PhpPact/FFI/Exception/InvalidResultException.php
src/PhpPact/FFI/Model/Result.php
tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php
tests/PhpPact/FFI/ClientTest.php

This is the first PR for wrapping ffi calls.
Currently, `$this->ffi->call()` and `$this->ffi->get()` accept arguments of any type, and return `mixed` value. There is no type safe. And static code analyzer (`phpstan`) will complain if we increase the level.
This PR replace calling `$this->ffi->call('pactffi_with_multipart_file_v2')` directly by creating a new method `withMultipartFileV2` which receive expected arguments and return expected value.

refactor: Wrap ffi call > pactffi_with_multipart_file_v2

---

helper/FFI/ClientTrait.php
src/PhpPact/Consumer/Driver/Interaction/AbstractDriver.php
src/PhpPact/FFI/Client.php
src/PhpPact/FFI/ClientInterface.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php
tests/PhpPact/FFI/ClientTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

refactor: Wrap ffi call > set interaction attributes methods

---

helper/FFI/ClientTrait.php
src/PhpPact/Consumer/Driver/Exception/InteractionNotModifiedException.php
src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php
src/PhpPact/FFI/Client.php
src/PhpPact/FFI/ClientInterface.php
src/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriver.php
tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php
tests/PhpPact/FFI/ClientTest.php
tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php

refactor: Wrap ffi call > setup interaction methods

---

.github/workflows/build.yml
README.md

Value of `PACT_DO_NOT_TRACK` need to be `true`, not `1`

fix: Fix wrong value of env PACT_DO_NOT_TRACK

---

helper/FFI/ClientTrait.php
src/PhpPact/Consumer/Service/MockServer.php
src/PhpPact/FFI/Client.php
src/PhpPact/FFI/ClientInterface.php
tests/PhpPact/Consumer/Service/MockServerTest.php
tests/PhpPact/FFI/ClientTest.php

refactor: Wrap ffi call > setup mock server methods

---

phpstan.neon

max level is currently `9`
Depends on:
* #663
* #664
* #665
* #666
* #667
* #668
* #669
* #670

chore: Update PHPStan level to max

---

compatibility-suite/public/generators/index.php
compatibility-suite/public/provider-states/index.php
composer.json
example/binary/provider/public/index.php
example/csv/provider/public/index.php
example/generators/provider/public/index.php
example/graphql/provider/public/index.php
example/json/provider/public/index.php
example/matchers/provider/public/index.php
example/message/provider/public/index.php
example/multipart/provider/public/index.php
example/protobuf-async-message/provider/public/index.php
example/xml/provider/public/index.php
helper/PhpProcess.php

Try to fix these issues:
* #672
* #641
* #549
[Slim Framework](https://www.slimframework.com/) + [PHP Built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php) -> slow
> The web server runs only one single-threaded process, so PHP applications will stall if a request is blocked. 
[Framework X](https://framework-x.org/) + [ReactPHP](https://reactphp.org/) -> faster 2x -> 4x
> Supports async and non-blocking execution for maximum performance
Another option is [AMPHP](https://amphp.org/http-server-router), but it's a bit slower, and the syntax is not  similar to Slim Framework than Framework X

refactor: Replace Slim Framework by Framework X

---

tests/PhpPact/Consumer/Matcher/Formatters/Expression/BooleanFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/ContentTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/DateTimeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/DecimalFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/EachKeyFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/EachValueFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/EqualityFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/IncludesFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/IntegerFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MatchAllFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MatchingFieldFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MinMaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MinTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/NotEmptyFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/NullValueFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/NumberFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/RegexFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/SemverFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/StringValueFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/TypeFormatterTest.php

Don't let json format interfere in strings comparition.

refactor: Compare strings directly

---

compatibility-suite/tests/Context/V3/Message/ConsumerContext.php
compatibility-suite/tests/Context/V4/CombinedContext.php
compatibility-suite/tests/Service/MessagePactWriter.php
compatibility-suite/tests/Service/MessagePactWriterInterface.php
compatibility-suite/tests/Service/PactWriter.php
compatibility-suite/tests/Service/PactWriterInterface.php
compatibility-suite/tests/Service/Server.php
compatibility-suite/tests/Service/SyncMessagePactWriter.php
compatibility-suite/tests/Service/SyncMessagePactWriterInterface.php
src/PhpPact/Config/Enum/WriteMode.php
src/PhpPact/Config/Exception/ConfigException.php
src/PhpPact/Config/Exception/InvalidWriteModeException.php
src/PhpPact/Config/PactConfig.php
src/PhpPact/Config/PactConfigInterface.php
src/PhpPact/Consumer/Driver/Pact/PactDriver.php
src/PhpPact/Consumer/Matcher/Enum/HttpStatus.php
src/PhpPact/Consumer/Matcher/Enum/UuidFormat.php
src/PhpPact/Consumer/Matcher/Generators/Uuid.php
src/PhpPact/Consumer/Matcher/HttpStatus.php
src/PhpPact/Consumer/Matcher/Matcher.php
src/PhpPact/Consumer/Matcher/Matchers/StatusCode.php
src/PhpPact/Consumer/Matcher/Model/Range.php
src/PhpPact/Consumer/Service/MockServer.php
tests/PhpPact/Config/PactConfigTest.php
tests/PhpPact/Consumer/Driver/Pact/PactDriverTest.php
tests/PhpPact/Consumer/Matcher/MatcherTest.php
tests/PhpPact/Consumer/Service/MockServerTest.php
tests/PhpPact/Standalone/MockServer/MockServerConfigTest.php

Keep old constants and ability to set string for some backward compatible.
For #260

refactor: Define enums

---

src/PhpPact/Consumer/Matcher/Formatters/Expression/AbstractExpressionFormatter.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/ContentTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/DateTimeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/EachKeyFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/EachValueFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/EqualityFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/IncludesFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MatchAllFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MatchingFieldFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MinMaxTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/MinTypeFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/NotEmptyFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/RegexFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/SemverFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/StringValueFormatterTest.php
tests/PhpPact/Consumer/Matcher/Formatters/Expression/TypeFormatterTest.php

Code:
https://github.com/pact-foundation/pact-reference/blob/f5ddf3d353149ae0fb539a1616eeb8544509fdfc/rust/pact_models/src/matchingrules/expressions.rs#L272-L273
Test:
https://github.com/pact-foundation/pact-reference/blob/f5ddf3d353149ae0fb539a1616eeb8544509fdfc/rust/pact_models/src/matchingrules/expressions.rs#L1785

feat: Support string contains single quote in matching expression

---

src/PhpPact/Consumer/Matcher/Generators/ProviderState.php
src/PhpPact/Consumer/Matcher/Matchers/AbstractDateTime.php
src/PhpPact/Consumer/Matcher/Matchers/Decimal.php
src/PhpPact/Consumer/Matcher/Matchers/Equality.php
src/PhpPact/Consumer/Matcher/Matchers/Integer.php
src/PhpPact/Consumer/Matcher/Matchers/NotEmpty.php
src/PhpPact/Consumer/Matcher/Matchers/Number.php
src/PhpPact/Consumer/Matcher/Matchers/Type.php
src/PhpPact/Consumer/Matcher/Model/Expression.php
src/PhpPact/Consumer/Matcher/Model/Generator/ExpressionFormattableInterface.php
src/PhpPact/Consumer/Matcher/Trait/ExpressionFormattableTrait.php
tests/PhpPact/Consumer/Matcher/Matchers/DateTest.php
tests/PhpPact/Consumer/Matcher/Matchers/DateTimeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/DecimalTest.php
tests/PhpPact/Consumer/Matcher/Matchers/EqualityTest.php
tests/PhpPact/Consumer/Matcher/Matchers/IntegerTest.php
tests/PhpPact/Consumer/Matcher/Matchers/NotEmptyTest.php
tests/PhpPact/Consumer/Matcher/Matchers/NumberTest.php
tests/PhpPact/Consumer/Matcher/Matchers/TimeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/TypeTest.php
tests/PhpPact/Consumer/Matcher/Model/ExpressionTest.php

Depends on #678
Support this syntax `matching(equalTo, fromProviderState('${Auth}', 'AST00004'))`

feat: Support fromProviderState generator in matching expression

---

compatibility-suite/public/provider-states/index.php
compatibility-suite/tests/Context/V1/Http/ProviderContext.php
compatibility-suite/tests/Context/V4/SyncMessage/ConsumerContext.php

refactor: Use 'never' return type

---

.github/workflows/compatibility-suite.yml
compatibility-suite/tests/Service/Server.php
src/PhpPact/Consumer/Driver/Pact/PactDriver.php
tests/PhpPact/Consumer/Driver/Pact/PactDriverTest.php
tests/PhpPact/Plugin/Driver/Pact/AbstractPluginPactDriverTestCase.php

* Fix the root cause described in https://github.com/pact-foundation/pact-php/issues/687#issuecomment-2425363210 for random issue like:
* #687
* #549
* #685
* Make mock server's clean up method idempotent
Depends on #686
Tested [150 times](https://github.com/pact-foundation/pact-php/actions/runs/11429024507/job/31803486191?pr=688).

fix(compatibility-suite): Clean up mock server

---

src/PhpPact/FFI/Client.php
src/PhpPact/FFI/ClientInterface.php
src/PhpPact/Log/Enum/LogLevel.php
src/PhpPact/Log/Exception/LogException.php
src/PhpPact/Log/Exception/LoggerApplyException.php
src/PhpPact/Log/Exception/LoggerAttachSinkException.php
src/PhpPact/Log/Exception/LoggerException.php
src/PhpPact/Log/Exception/LoggerUnserializeException.php
src/PhpPact/Log/Logger.php
src/PhpPact/Log/LoggerInterface.php
src/PhpPact/Log/Model/AbstractSink.php
src/PhpPact/Log/Model/Buffer.php
src/PhpPact/Log/Model/File.php
src/PhpPact/Log/Model/SinkInterface.php
src/PhpPact/Log/Model/Stderr.php
src/PhpPact/Log/Model/Stdout.php
src/PhpPact/Log/PHPUnit/PactLoggingExtension.php
src/PhpPact/Log/PHPUnit/PactLoggingSubscriber.php
tests/PhpPact/FFI/ClientTest.php
tests/PhpPact/Log/LoggerTest.php
tests/PhpPact/Log/Model/BufferTest.php
tests/PhpPact/Log/Model/FileTest.php
tests/PhpPact/Log/Model/StderrTest.php
tests/PhpPact/Log/Model/StdoutTest.php
tests/PhpPact/Log/PHPUnit/PactLoggingSubscriberTest.php

* Allow logging to multiple sinks: file, buffer, stdout, stderr
* Usage
```php
$logger = Logger::instance();
$logger->attach(new File('/path/to/file', LogLevel::DEBUG));
$logger->attach(new Buffer(LogLevel::ERROR));
$logger->attach(new Stdout(LogLevel::WARN));
$logger->attach(new Stderr(LogLevel::INFO));
$logger->apply();
````
* Add PHPUnit logging extension
* It define sinks base on values of `PACT_LOGLEVEL` and `PACT_LOG` then apply logger. These environment variables are already defined from v9 but only `PACT_LOGLEVEL` is used in v10
* Implements #341
* Usage
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="./autoload.php" colors="true">
<testsuites>
<testsuite name="PhpPact Example Tests">
<directory>./tests</directory>
</testsuite>
</testsuites>
<php>
<env …
```

feat: Allow logging to multiple sinks

---

.github/workflows/build.yml

PHP 8.4.1 has been released. This PR add that version into the list of PHP versions for unit testing.

ci: Test PHP 8.4

---

tests/PhpPact/Consumer/MessageBuilderTest.php

Fix this error:
```
Method PhpPactTest\Consumer\MessageBuilderTest::getCallbacks() should return array<int|string, callable():  
mixed> but returns array. 
```

style: Fix method return type hint

---

composer.json
src/PhpPact/FFI/Model/ArrayData.php
src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
src/PhpPact/Standalone/StubService/StubServer.php
tests/PhpPact/FFI/ClientTest.php
tests/PhpPact/FFI/Model/ArrayDataTest.php
tests/PhpPact/Log/LoggerTest.php

~~Wait for new version of Rector https://github.com/rectorphp/rector/issues/8815~~

deps: Upgrade to PHPStan 2.0

---

compatibility-suite/tests/Service/MatchingRuleConverter.php
src/PhpPact/Consumer/Matcher/Exception/InvalidRegexException.php
src/PhpPact/Consumer/Matcher/Matchers/Regex.php
tests/PhpPact/Consumer/Matcher/Matchers/EachValueTest.php
tests/PhpPact/Consumer/Matcher/Matchers/RegexTest.php

* Follow suggestion from @mefellows : the value must be correct type, no need to validate beforehand
* This change allows the use of an empty string (`''`) instead of `null` as an example value when a generator is set. This way, we don't need to find a value that matches the regex, since the generator will replace that value later anyway.

chore: Don't validate example value with regex

---

README.md
docs/troubleshooting.md

Add document for this change https://github.com/pact-foundation/pact-php/pull/689

docs: Add troubleshooting doc (logging)

---

.github/renovate.json

`docker-compose.yml` is not used anywhere. It's just an example file. We can tell Renovate to ignore that file, prevent it from keep pinning dependencies on that file.

deps: Tell renovate to ignore docker-compose.yml

---

composer.json
src/PhpPact/FFI/Model/ArrayData.php
tests/PhpPact/FFI/Model/ArrayDataTest.php

PHPStan [2.0.4](https://github.com/phpstan/phpstan/releases/tag/2.0.4) introduce new change that don't report the error `offsetAccess.nonOffsetAccessible` on PHP's `CDATA` anymore.

fix: Fix PHPStan no error to ignore

---

composer.json
example/form-urlencoded/consumer/autoload.php
example/form-urlencoded/consumer/phpunit.xml
example/form-urlencoded/consumer/src/Service/HttpClientService.php
example/form-urlencoded/consumer/tests/Service/HttpClientServiceTest.php
example/form-urlencoded/pacts/formUrlEncodedConsumer-formUrlEncodedProvider.json
example/form-urlencoded/provider/autoload.php
example/form-urlencoded/provider/phpunit.xml
example/form-urlencoded/provider/public/index.php
example/form-urlencoded/provider/tests/PactVerifyTest.php

* Add form urlencoded example with matchers
* Add custom headers example
Depend on:
* https://github.com/pact-foundation/roadmap/pull/99
* https://github.com/pact-foundation/pact-reference/pull/464
* https://github.com/pact-foundation/pact-reference/pull/463
* https://github.com/pact-foundation/pact-reference/pull/462
* https://github.com/pact-foundation/pact-reference/pull/478
* https://github.com/pact-foundation/pact-php/pull/696
* https://github.com/pact-foundation/pact-php/pull/701
* https://github.com/pact-foundation/pact-php/pull/709

chore: Add form urlencoded example

---

.github/workflows/build.yml
.github/workflows/compatibility-suite.yml

Triggering on all 'push' and 'pull_request' events will result in duplicated CI runs in PRs (due to both conditions being met).
Instead, trigger only on pushes to `master`, or updates to PRs targetting `master`.
Also removed cron job as all updates to `master` are checked anyway.

chore(ci): prevent duplicate ci triggers

---

src/PhpPact/FFI/Client.php
src/PhpPact/FFI/ClientInterface.php

fix: Revert breaking changes to FFI\Client::call and FFI\Client::get

---

tests/PhpPact/Log/LoggerTest.php

PHPStan report these 2 errors in https://github.com/pact-foundation/pact-php/pull/724/files:
* Offset 'args' might not exist on array{args: array{literal-string&non-falsy-string, 1|2|3|4}, return: 0}|null.
* Offset 'return' might not exist on array{args: array{literal-string&non-falsy-string, 1|2|3|4}, return: 0}|null.
This PR solve them.

test: Fix 'offset might not exist on array' errors

---

src/PhpPact/Consumer/Matcher/Matchers/MaxType.php
src/PhpPact/Consumer/Matcher/Matchers/MinMaxType.php
src/PhpPact/Consumer/Matcher/Matchers/MinType.php
tests/PhpPact/Consumer/Matcher/Matchers/MaxTypeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MinMaxTypeTest.php
tests/PhpPact/Consumer/Matcher/Matchers/MinTypeTest.php

The syntax `atLeast(1), atMost(2), eachValue(matching(type, 'text'))` is allowed in the documents:
* https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_models/src/matchingrules/expressions.rs#L101-L104
* https://github.com/pactflow/pact-protobuf-plugin?tab=readme-ov-file#matching-repeated-fields
But it is not working as expected. It's probably a bug. We will track it at https://github.com/pactflow/pact-protobuf-plugin/issues/179
This pull request is a temporary solution: move `eachValue` to the beginning of the expression:
`eachValue(matching(type, 'text')), atLeast(1), atMost(2)`

fix: Fix matching rules not working with protobuf's repeated field
