pact-foundation/pact-php

src/Mocks/MockHttpService/Mappers/ProviderServiceRequestMapper.php, src/Mocks/MockHttpService/Mappers/ProviderServiceResponseMapper.php, src/Mocks/MockHttpService/Models/IHttpMessage.php, src/Mocks/MockHttpService/Models/ProviderServiceRequest.php, src/Mocks/MockHttpService/Models/ProviderServiceResponse.php
See https://github.com/pact-foundation/pact-php/issues/7
=> Always return headers as array

composer.json
Hello guys,
I'm working on several symfony 4 projects and we used your wonderful pact implementation for about a month. I used a hard copy of yours and had adjusted the composer.json like in this pull request and it works like a charm. I would really appreciate if you could merge this. 
Thx,
lyhl
=> Make phppact working with symfony 4

src/PhpPact/Standalone/ProviderVerifier/Verifier.php
=> Use Process for symfony/process v4 compatibility

composer.json, src/PhpPact/Provider/MessageVerifier.php, src/PhpPact/Standalone/Runner/ProcessRunner.php, tests/PhpPact/Standalone/Runner/ProcessRunnerTest.php
This fixes windows processes and allows them to run in background
I had to upgrade the Amp packages
=> Fix issue #124 unstable windows processes

src/PhpPact/Provider/MessageVerifier.php, src/PhpPact/Standalone/ProviderVerifier/VerifierProcess.php, src/PhpPact/Standalone/Runner/ProcessRunner.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
=> Merging Loose logging #125

src/PhpPact/Consumer/Listener/PactTestListener.php
=> Tag the Consumer before publishing the Pact to the Broker

src/PhpPact/Standalone/MockService/MockServerEnvConfig.php
To allow to set server log path from phpunit.xml
=> Adding possibility to add server log path config from env/phpunit xml

src/PhpPact/Consumer/Hook/ContractDownloader.php
@cfmack My last PR contained a bug. As part of the refactoring, I removed a private variable that was used later.
=> Fix missing client

src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
This PR gives the allows setting the providers' version tag while verifying.
=> Allow setting provider version tag

example/pacts/someconsumer-someprovider.json, example/pacts/test_consumer-test_provider.json, example/tests/Provider/PactVerifyTest.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php
branching fail.  I'm sure there's a meme for this
=> json file is actually located in the pacts folder #151

README.md, script/create-pr-to-update-pact-ruby-standalone.sh, src/PhpPact/Standalone/Installer/Service/InstallerLinux.php, src/PhpPact/Standalone/Installer/Service/InstallerMac.php, src/PhpPact/Standalone/Installer/Service/InstallerWindows.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php
Please expose the --log-dir and --log-level options to the native API.
=> feat: update standalone to 1.86.0

.travis.yml, composer.json, example/pacts/test_consumer-test_provider.json, example/phpunit.all.xml, example/phpunit.core.xml, example/tests/MessageProvider/ExampleMessageProviderTest.php, src/PhpPact/Provider/MessageVerifier.php, src/PhpPact/Standalone/MockService/MockServer.php, src/PhpPact/Standalone/MockService/MockServerConfig.php, src/PhpPact/Standalone/MockService/MockServerEnvConfig.php, src/PhpPact/Standalone/StubService/StubServer.php, tests/PhpPact/Standalone/StubServer/Service/StubServerHttpServiceTest.php
Updated amp and modified failed message provider tests
=> when classmap authoritative true on composer, deprecation warning #150

README.md, src/PhpPact/Standalone/Installer/Service/InstallerLinux.php, src/PhpPact/Standalone/Installer/Service/InstallerMac.php, src/PhpPact/Standalone/Installer/Service/InstallerWindows.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
added the wip and pending features + updated ruby standalone to supported version + readme. Kindly please check
=> feat: pending pact feature

src/PhpPact/Consumer/Hook/ContractDownloader.php
Fixed missing code argument to prevent a fatal error.
See https://www.php.net/manual/de/exception.construct.php
=> Fixed fatal error.

src/PhpPact/Provider/MessageVerifier.php
Added warning log with stderr in case of validation failure.
=> Added warning log in case of validation failure.

composer.json, src/PhpPact/Provider/MessageVerifier.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
=> Added support for multiple provider and consumer version tags.

src/PhpPact/Standalone/MockService/MockServer.php
=> Escaped shell args.

phpunit.xml, src/PhpPact/Standalone/MockService/MockServer.php, src/PhpPact/Standalone/MockService/MockServerConfig.php, src/PhpPact/Standalone/MockService/MockServerEnvConfig.php, src/PhpPact/Standalone/PactConfigInterface.php, src/PhpPact/Standalone/PactMessage/PactMessageConfig.php
=> Added loglevel to the mockservice.

src/PhpPact/Standalone/Installer/Model/Scripts.php, src/PhpPact/Standalone/Installer/Service/InstallerLinux.php, src/PhpPact/Standalone/Installer/Service/InstallerMac.php, src/PhpPact/Standalone/Installer/Service/InstallerWindows.php
=> Updated standalone binaries to 1.88.14 and added pact-broker cmd.

README.md, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
Added filterRequest feature by implement guzzle request callback handler as config value.
Needed documentation and tests - so it is declared as a draft for now.
Closes #164
=> Added filterRequest

.travis.yml, appveyor.yml, composer.json, example/src/Provider/public/index.php, example/tests/MessageConsumer/ExampleMessageConsumerTest.php, example/tests/Provider/PactVerifyTest.php, phpunit.xml, tests/PhpPact/Consumer/InteractionBuilderTest.php, tests/PhpPact/Consumer/Matcher/MatcherTest.php, tests/PhpPact/Standalone/MockServer/Service/MockServerHttpServiceTest.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierProcessTest.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php, tests/PhpPact/Standalone/Runner/ProcessRunnerTest.php, tests/PhpPact/Standalone/StubServer/Service/StubServerHttpServiceTest.php
Updated composer deps.
* Changed PHP min version to 7.3
* Updated all composer deps to the latest stable ones
* Guzzle 7
* Slim 4
* Fixed test execution under PHPUnit 9
Fixes #180 
Supersedes #179
=> feat: Updated dependencies

src/PhpPact/Standalone/Broker/Broker.php, src/PhpPact/Standalone/Broker/BrokerConfig.php, src/PhpPact/Standalone/Installer/Service/InstallerLinux.php, src/PhpPact/Standalone/Installer/Service/InstallerMac.php, src/PhpPact/Standalone/Installer/Service/InstallerWindows.php, tests/PhpPact/Standalone/Broker/BrokerConfigTest.php, tests/PhpPact/Standalone/Broker/BrokerTest.php
Not all arguments included but a starting point 😃
=> feat: Added pact-broker standalone

README.md
and remove travis and appveyor badges.
Closes #188
=> feat: Add github actions badge

src/PhpPact/Consumer/Hook/ContractDownloader.php, src/PhpPact/Consumer/Listener/PactTestListener.php, src/PhpPact/Consumer/Matcher/Matcher.php, src/PhpPact/Consumer/MessageBuilder.php, src/PhpPact/Consumer/Model/Message.php, src/PhpPact/Standalone/Installer/InstallManager.php, src/PhpPact/Standalone/Installer/Service/InstallerLinux.php, src/PhpPact/Standalone/Installer/Service/InstallerMac.php, src/PhpPact/Standalone/Installer/Service/InstallerWindows.php, src/PhpPact/Standalone/MockService/MockServer.php, src/PhpPact/Standalone/MockService/MockServerConfig.php, src/PhpPact/Standalone/MockService/MockServerEnvConfig.php, src/PhpPact/Standalone/PactConfigInterface.php, src/PhpPact/Standalone/PactMessage/PactMessageConfig.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, src/PhpPact/Standalone/StubService/StubServer.php
fixes #191 type hints based on phpstan level 5 analysis
=> fix type hints

src/PhpPact/Consumer/Model/ConsumerRequest.php, src/PhpPact/Consumer/Model/ProviderResponse.php, src/PhpPact/Standalone/Installer/Service/InstallerLinux.php, src/PhpPact/Standalone/Installer/Service/InstallerMac.php, src/PhpPact/Standalone/Installer/Service/InstallerWindows.php, src/PhpPact/Standalone/ProviderVerifier/Model/ConsumerVersionSelectors.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfig.php, src/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
Making changes and adjusting Windows tests on top of  feat: add consumer version selectors support #204
=> feat: Add Selectors Consumer Version Selectors

README.md, composer.json
Adjusting for changes outside of #209 , I was able to pass tests on the lower version of composer/semver.  I also updated the readme file while I was at it to point to the right packagist location
=> Reduce semver req

example/src/Consumer/publish_json_example.php, src/PhpPact/Broker/Service/BrokerHttpClient.php, src/PhpPact/Consumer/Listener/PactTestListener.php
=> fix: parameter order mismatch

composer.json
This can help improve compatibility with different setups
=> support: Improve guzzlehttp/guzzle version compatibility 

composer.json
https://github.com/advisories/GHSA-q559-8m2m-g699
=> guzzle security update

example/src/MessageConsumer/receive.php, example/tests/Provider/PactVerifyTest.php
Fixes the first step of the pipeline.
=> php-cs-fixer

src/PhpPact/Consumer/Model/ConsumerRequest.php, tests/PhpPact/Consumer/Model/ConsumerRequestTest.php
Added matchers support in the ConsumerRequest path in order to use path variables
=> feat: Support matchers in path

.github/workflows/build.yml
This PR follow suggestion from the custom action's home page:
> Warning You probably don't need to install this custom action.
https://github.com/styfle/cancel-workflow-action#readme
=> Use Github Actions feature to cancel previous runs

RELEASING.md
Taken a first pass at some releasing instructions based on what I can glean from the current setup.
=> docs: releasing instructions

.github/dependabot.yml
As per one of the tasks in #254 
Create a dependabot config to allow for automated testing of dependency updates
=> deps(ci): create dependabot config

example/binary/provider/tests/PactVerifyTest.php, example/json/provider/tests/PactVerifyTest.php, example/message/provider/tests/PactVerifyTest.php, example/multipart/provider/tests/PactVerifyTest.php, tests/PhpPact/Helper/ProviderProcess.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
* Move provider process code to helper class to re-use, reduce duplicated code
* Print out provider process' log to help debugging
=> Print provider process's log

composer.json, example/matchers/consumer/phpunit.xml, example/matchers/consumer/src/Service/HttpClientService.php, example/matchers/consumer/tests/Service/MatchersTest.php, example/matchers/pacts/matchersConsumer-matchersProvider.json, example/matchers/provider/phpunit.xml, example/matchers/provider/public/index.php, example/matchers/provider/tests/PactVerifyTest.php, phpunit.xml
* This example demonstrate how to use matchers, and how they behave in consumer and provider tests
* This act as test cases for future changes to matchers
* Example for query & header matchers will be added later (in other PR), after waiting for response from these threads:
* https://pact-foundation.slack.com/archives/C02BXLDJ7JR/p1698024661692909
* https://pact-foundation.slack.com/archives/C02BXLDJ7JR/p1698024666918839
* Example for generators will be added later (in other PR)
=> chore: Add matchers example

example/matchers/consumer/tests/Service/MatchersTest.php, example/matchers/pacts/matchersConsumer-matchersProvider.json, example/matchers/provider/public/index.php, src/PhpPact/Consumer/Matcher/Matcher.php, tests/PhpPact/Consumer/Matcher/MatcherTest.php
This is a specification v4's matcher
=> feat: Add eachValue matcher

example/matchers/consumer/tests/Service/MatchersTest.php, example/matchers/pacts/matchersConsumer-matchersProvider.json, example/matchers/provider/public/index.php, src/PhpPact/Consumer/Matcher/Matcher.php, tests/PhpPact/Consumer/Matcher/MatcherTest.php
This is a specification v4's matcher
=> feat: Add eachKey matcher

src/PhpPact/Standalone/ProviderVerifier/Model/VerifierLoggerInterface.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php
This change is for implementing compatibility suite
=> feat: Allow capture verifier output

src/PhpPact/Consumer/Matcher/Generators/RandomInt.php, src/PhpPact/Consumer/Matcher/Model/GeneratorInterface.php, tests/PhpPact/Consumer/Matcher/Generators/RandomIntTest.php
=> refactor: Add RandomInt generator class

src/PhpPact/Consumer/Matcher/Generators/RandomHexadecimal.php, tests/PhpPact/Consumer/Matcher/Generators/RandomHexadecimalTest.php
=> refactor: Add RandomHexadecimal generator class

src/PhpPact/Consumer/Matcher/Generators/RandomString.php, tests/PhpPact/Consumer/Matcher/Generators/RandomStringTest.php
=> refactor: Add RandomString generator class

src/PhpPact/Consumer/Matcher/Generators/Regex.php, tests/PhpPact/Consumer/Matcher/Generators/RegexTest.php
=> refactor: Add Regex generator class

src/PhpPact/Consumer/Matcher/Generators/AbstractDateTime.php, src/PhpPact/Consumer/Matcher/Generators/Date.php, tests/PhpPact/Consumer/Matcher/Generators/DateTest.php
=> refactor: Add Date generator class

src/PhpPact/Consumer/Matcher/Generators/AbstractDateTime.php, src/PhpPact/Consumer/Matcher/Generators/Date.php, src/PhpPact/Consumer/Matcher/Generators/Time.php, tests/PhpPact/Consumer/Matcher/Generators/DateTest.php, tests/PhpPact/Consumer/Matcher/Generators/TimeTest.php
Depend on https://github.com/pact-foundation/pact-php/pull/383
=> refactor: Add Time generator class

src/PhpPact/Consumer/Matcher/Generators/AbstractDateTime.php, src/PhpPact/Consumer/Matcher/Generators/Date.php, src/PhpPact/Consumer/Matcher/Generators/DateTime.php, tests/PhpPact/Consumer/Matcher/Generators/DateTest.php, tests/PhpPact/Consumer/Matcher/Generators/DateTimeTest.php
Depend on https://github.com/pact-foundation/pact-php/pull/383
=> refactor: Add DateTime generator class

src/PhpPact/Consumer/Matcher/Generators/RandomBoolean.php, tests/PhpPact/Consumer/Matcher/Generators/RandomBooleanTest.php
=> refactor: Add RandomBoolean generator class

src/PhpPact/Consumer/Matcher/Generators/ProviderState.php, tests/PhpPact/Consumer/Matcher/Generators/ProviderStateTest.php
=> refactor: Add ProviderState generator class

src/PhpPact/Consumer/Matcher/Matchers/AbstractDateTime.php, src/PhpPact/Consumer/Matcher/Matchers/Date.php, tests/PhpPact/Consumer/Matcher/Matchers/DateTest.php
=> refactor: Add Date matcher class

src/PhpPact/Consumer/Matcher/Matchers/AbstractDateTime.php, src/PhpPact/Consumer/Matcher/Matchers/Date.php, src/PhpPact/Consumer/Matcher/Matchers/Time.php, tests/PhpPact/Consumer/Matcher/Matchers/DateTest.php, tests/PhpPact/Consumer/Matcher/Matchers/TimeTest.php
Depend on https://github.com/pact-foundation/pact-php/pull/394
=> refactor: Add Time matcher class

src/PhpPact/Consumer/Matcher/Matchers/AbstractDateTime.php, src/PhpPact/Consumer/Matcher/Matchers/Date.php, src/PhpPact/Consumer/Matcher/Matchers/DateTime.php, tests/PhpPact/Consumer/Matcher/Matchers/DateTest.php, tests/PhpPact/Consumer/Matcher/Matchers/DateTimeTest.php
Depend on https://github.com/pact-foundation/pact-php/pull/394
=> refactor: Add DateTime matcher class

src/PhpPact/Consumer/Matcher/Matchers/Boolean.php, tests/PhpPact/Consumer/Matcher/Matchers/BooleanTest.php
=> refactor: Add Boolean matcher class

src/PhpPact/Consumer/Matcher/Matchers/Decimal.php, tests/PhpPact/Consumer/Matcher/Matchers/DecimalTest.php
=> refactor: Add Decimal matcher class

src/PhpPact/Consumer/Matcher/Matchers/Integer.php, tests/PhpPact/Consumer/Matcher/Matchers/IntegerTest.php
=> refactor: Add Integer matcher class

src/PhpPact/Consumer/Matcher/Exception/InvalidHttpStatusException.php, src/PhpPact/Consumer/Matcher/Matchers/StatusCode.php, tests/PhpPact/Consumer/Matcher/Matchers/StatusCodeTest.php
=> refactor: Add StatusCode matcher class

src/PhpPact/Consumer/Matcher/Matchers/Values.php, tests/PhpPact/Consumer/Matcher/Matchers/ValuesTest.php
=> refactor: Add Values matcher class

src/PhpPact/Consumer/Matcher/Matchers/MinMaxType.php, tests/PhpPact/Consumer/Matcher/Matchers/MinMaxTypeTest.php
=> refactor: Add MinMaxType matcher class

compatibility-suite/tests/Exception/CompatibilitySuiteException.php, compatibility-suite/tests/Exception/FixtureNotFoundException.php, compatibility-suite/tests/Exception/InvalidJsonFixtureException.php, compatibility-suite/tests/Model/Xml.php, compatibility-suite/tests/Service/FixtureLoader.php, compatibility-suite/tests/Service/FixtureLoaderInterface.php, compatibility-suite/tests/Service/InteractionBuilder.php, compatibility-suite/tests/Service/InteractionBuilderInterface.php, compatibility-suite/tests/Service/Parser.php, compatibility-suite/tests/Service/ParserInterface.php, compatibility-suite/tests/Service/RequestBuilder.php, compatibility-suite/tests/Service/RequestBuilderInterface.php, compatibility-suite/tests/Service/ResponseBuilder.php, compatibility-suite/tests/Service/ResponseBuilderInterface.php
* Add `InteractionBuilder` (+ related services)
* About the code in `Parser` and `FixtureLoader` services, I copied most of the logic from these code:
* https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/tests/shared_steps/mod.rs
* https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_models/src/headers.rs
* https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_models/src/query_strings.rs
I deleted code that's not related. Will add back in future PR.
Hope the PR is not too big.
=> test(compatibility-suite): Add InteractionBuilder service

example/xml/consumer/src/Service/HttpClientService.php, example/xml/consumer/tests/Service/HttpClientServiceTest.php, example/xml/pacts/xmlConsumer-xmlProvider.json, example/xml/provider/public/index.php
* Add header's matcher example (copy from pact-js)
* Change example value to verify that matchers are working
* Add attribute's matcher example
* Add content's generator example (copy from pact-js, commented out, waiting for support from Rust-core)
* Add assertions
=> test: Update xml example

example/binary/pacts/binaryConsumer-binaryProvider.json, example/csv/pacts/csvConsumer-csvProvider.json, example/generators/pacts/generatorsConsumer-generatorsProvider.json, example/json/pacts/jsonConsumer-jsonProvider.json, example/message/pacts/messageConsumer-messageProvider.json, example/multipart/pacts/multipartConsumer-multipartProvider.json, example/protobuf-async-message/pacts/protobufAsyncMessageConsumer-protobufAsyncMessageProvider.json, example/protobuf-sync-message/pacts/protobufSyncMessageConsumer-protobufSyncMessageProvider.json, example/xml/pacts/xmlConsumer-xmlProvider.json
Update remaining pacts when updating to 0.4.13 #449
=> chore: Update remaining pacts for 0.4.13

composer.json, example/binary/pacts/binaryConsumer-binaryProvider.json, example/csv/pacts/csvConsumer-csvProvider.json, example/generators/pacts/generatorsConsumer-generatorsProvider.json, example/json/pacts/jsonConsumer-jsonProvider.json, example/matchers/pacts/matchersConsumer-matchersProvider.json, example/message/consumer/src/ExampleMessageConsumer.php, example/message/pacts/messageConsumer-messageProvider.json, example/multipart/pacts/multipartConsumer-multipartProvider.json, example/protobuf-async-message/pacts/protobufAsyncMessageConsumer-protobufAsyncMessageProvider.json, example/protobuf-sync-message/pacts/protobufSyncMessageConsumer-protobufSyncMessageProvider.json, example/xml/pacts/xmlConsumer-xmlProvider.json, src/PhpPact/Config/LogLevelTrait.php, tests/PhpPact/Helper/AbstractProcess.php
For #419
Allow to turn off logs by running `PACT_LOGLEVEL=off phpunit` or `PACT_LOGLEVEL=none phpunit`
=> feat: Allow turn off log

composer.json
RE: https://github.com/pact-foundation/pact-ruby-standalone/pull/131
=> chore(deps): update to pact-ruby-standalone-v2.4.1

.github/workflows/build.yml, .gitignore, composer.json, example/generators/consumer/tests/Service/GeneratorsTest.php, phpunit.xml, tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php, tests/PhpPact/Consumer/Matcher/MatcherTest.php, tests/PhpPact/Consumer/Matcher/Matchers/GeneratorAwareMatcherTestCase.php, tests/PhpPact/Consumer/Matcher/Matchers/MatchingFieldTest.php
* Since php is upgraded to ^8.1, phpunit can be upgrade to ^10
* `assertRegExp` is no longer available in phpunit 10
=> Upgrade phpunit

example/csv/pacts/csvConsumer-csvProvider.json, example/protobuf-async-message/pacts/protobufAsyncMessageConsumer-protobufAsyncMessageProvider.json, example/protobuf-sync-message/pacts/protobufSyncMessageConsumer-protobufSyncMessageProvider.json
Update plugin versions in pacts, as if they are created by latest version of these plugins
=> chore: Update plugin versions in pacts

.github/workflows/compatibility-suite.yml, compatibility-suite/suites/v3/message/provider.yml
* Update compatibility suite to latest commit
* Use wip tag
=> ci(compatibility-suite): Use w.i.p tag

src/PhpPact/Consumer/Driver/InteractionPart/AbstractInteractionPartDriver.php, src/PhpPact/Consumer/Driver/InteractionPart/RequestDriver.php, src/PhpPact/Consumer/Driver/InteractionPart/RequestDriverInterface.php, src/PhpPact/Consumer/Driver/InteractionPart/ResponseDriver.php, src/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverInterface.php, tests/PhpPact/Consumer/Driver/InteractionPart/RequestDriverTest.php, tests/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverTest.php
* Add part drivers (code taken from part registry)
* Add tests for part drivers
=> refactor: Add interaction part drivers

.github/workflows/compatibility-suite.yml
To remove node's version warnings
=> ci(compatibility-suite): Update Github Actions

src/PhpPact/Consumer/Exception/MissingCallbackException.php, src/PhpPact/Consumer/MessageBuilder.php, tests/PhpPact/Consumer/MessageBuilderTest.php
* Add default value for `$callback` property
* Add `MissingCallbackException`
* Add `MessageBuilderTest`
=> test: Test MessageBuilder

tests/PhpPact/Consumer/Model/Body/MultipartTest.php, tests/PhpPact/Consumer/Model/Body/PartTest.php, tests/PhpPact/Consumer/Model/Body/TextTest.php
Depend on https://github.com/pact-foundation/pact-php/pull/525
=> test: Test body models

tests/PhpPact/Standalone/ProviderVerifier/Model/VerifierConfigTest.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
Rewrite `VerifierConfigTest` to increase code coverage
=> test: Test VerifierConfig

tests/PhpPact/Consumer/Model/ConsumerRequestTest.php, tests/PhpPact/Consumer/Model/MessageTest.php, tests/PhpPact/Consumer/Model/ProviderResponseTest.php
Depend on https://github.com/pact-foundation/pact-php/pull/532
=> test: Test body for interaction/message

tests/PhpPact/Consumer/Service/MockServerTest.php, tests/PhpPact/Plugins/Protobuf/Service/GrpcMockServerTest.php
* Reuse `ClientTrait`
* Add `GrpcMockServerTest`
=> test: Test GrpcMockServer

composer.json
- Symfony 4.4 is end of life.
- Symfony 7.0 is new supported version
=> deps: Upgrade symfony/process

tests/PhpPact/FFI/Model/ArrayDataTest.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
This PR test behavior when some verifier's config is empty array.
https://github.com/pact-foundation/pact-php/pull/527 is now part of this PR
=> test: Test verifier with empty array config

src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
> setProviderState and setFilterInfo function names got interchanged 
Thanks @silverblaze404  for pointing this mistake out.
=> fix: Swap implementation of setFilterInfo() and setProviderState()

example/matchers/consumer/src/Service/HttpClientService.php, example/matchers/consumer/tests/Service/MatchersTest.php, example/matchers/pacts/matchersConsumer-matchersProvider.json
Depend on https://github.com/pact-foundation/pact-php/pull/551
=> chore: arrayContains and eachValue example for query and header

example/matchers/consumer/tests/Service/MatchersTest.php
* Add pros and cons for alternative approach
* Add spaces between comments and code
=> docs: Make comments more readable

README.md
My bad, it's copy paste without changing issue.
=> docs: Fix wrong variable

README.md
An advertisement to my personal projects
=> docs: Add Framework Integrations section to readme

docs/ADDITIONAL-EXAMPLES.md
Add a bit more context to the additional examples page
=> docs: Update ADDITIONAL-EXAMPLES.md

src/PhpPact/Consumer/Matcher/Formatters/PluginFormatter.php, src/PhpPact/Consumer/Matcher/Matchers/MatchingField.php, tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php
There are a lot of `if` conditions in `PluginFormatter`. I think `Visitor` pattern can be applied to solve this.
=> refactor: Apply Visitor pattern for MatchingField matcher

src/PhpPact/Consumer/Matcher/Formatters/PluginFormatter.php, src/PhpPact/Consumer/Matcher/Matchers/NotEmpty.php, tests/PhpPact/Consumer/Matcher/Formatters/PluginFormatterTest.php, tests/PhpPact/Consumer/Matcher/Matchers/NotEmptyTest.php
Reverts pact-foundation/pact-php#590
=> Revert "refactor: Apply Visitor pattern for NotEmpty matcher"

README.md, docs/consumer.md, docs/framework-integrations.md, docs/messages.md, docs/provider.md, docs/stub-server.md
* Use structure from pact-js/pact-go
* There are no workshop for pact-php, so I remove that section
* Change version of platform `windows x86 ` from `All` to `9.x -` https://github.com/pact-foundation/pact-php/issues/600
=> docs: Refactor readme using structure from pact-js

composer.json
Reverts pact-foundation/pact-php#611
Because of this https://github.com/pact-foundation/pact-reference/issues/416#issuecomment-2111327781
=> Revert "deps: Update ffi library to 0.4.20"

composer.json, example/binary/consumer/tests/Service/HttpClientServiceTest.php, example/multipart/consumer/tests/Service/HttpClientServiceTest.php
Release of https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.21
=> fix: update libpact_ffi to 0.4.21

.github/workflows/build.yml, composer.json, phpunit.xml
See description at https://github.com/pact-foundation/pact-php/pull/633#issuecomment-2366848947
=> ci: Run all examples at once on windows

example/graphql/provider/public/index.php
Use Slim Framework's body parsing feature
Depend on https://github.com/pact-foundation/pact-php/pull/638
=> Use body parsing middleware

compatibility-suite/public/provider-states/index.php, composer.json, example/message/consumer/src/receive.php, rector.php, tests/PhpPact/Standalone/MockServer/MockServerEnvConfigTest.php
Install rector to help auto refactor to new php syntax
For #260
=> refactor: Install rector and auto refactor

example/binary/consumer/src/Service/HttpClientService.php, example/csv/consumer/src/Service/HttpClientService.php, example/generators/consumer/src/Service/HttpClientService.php, example/graphql/consumer/src/Service/HttpClientService.php, example/json/consumer/src/Service/HttpClientService.php, example/matchers/consumer/src/Service/HttpClientService.php, example/multipart/consumer/src/Service/HttpClientService.php, example/stub-server/consumer/src/Service/HttpClientService.php, example/xml/consumer/src/Service/HttpClientService.php
=> refactor: Use PHP 8.0 constructor property promotion feature

src/PhpPact/Consumer/Driver/Body/InteractionBodyDriver.php, src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, tests/PhpPact/Consumer/Driver/Body/InteractionBodyDriverTest.php, tests/PhpPact/FFI/ClientTest.php
=> refactor: Wrap ffi call > pactffi_with_body

src/PhpPact/Consumer/Driver/Body/MessageBodyDriver.php, tests/PhpPact/Consumer/Driver/Body/MessageBodyDriverTest.php
=> refactor: Use ffi call wrappers

src/PhpPact/Consumer/Driver/Pact/PactDriver.php, src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, src/PhpPact/Plugin/Driver/Pact/AbstractPluginPactDriver.php, tests/PhpPact/Consumer/Driver/Pact/PactDriverTest.php, tests/PhpPact/FFI/ClientTest.php
=> refactor: Wrap ffi call > get specification enum methods

src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, tests/PhpPact/FFI/ClientTest.php
=> refactor: FFI client hide get() method

helper/FFI/ClientTrait.php, src/PhpPact/Consumer/Driver/Interaction/AbstractMessageDriver.php, src/PhpPact/Consumer/Driver/Interaction/InteractionDriver.php, src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, src/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriver.php, tests/PhpPact/Consumer/Driver/Interaction/InteractionDriverTest.php, tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php, tests/PhpPact/FFI/ClientTest.php, tests/PhpPact/SyncMessage/Driver/Interaction/SyncMessageDriverTest.php
=> refactor: Wrap ffi call > new interaction methods

helper/FFI/ClientTrait.php, src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, src/PhpPact/Standalone/ProviderVerifier/Exception/InvalidVerifierHandleException.php, src/PhpPact/Standalone/ProviderVerifier/Exception/VerifierNotCreatedException.php, src/PhpPact/Standalone/ProviderVerifier/Verifier.php, tests/PhpPact/FFI/ClientTest.php, tests/PhpPact/Standalone/ProviderVerifier/VerifierTest.php
=> refactor: Wrap ffi call > setup verifier methods

helper/FFI/ClientTrait.php, src/PhpPact/Consumer/Driver/Exception/HeaderNotAddedException.php, src/PhpPact/Consumer/Driver/Exception/QueryParameterNotAddedException.php, src/PhpPact/Consumer/Driver/Interaction/MessageDriver.php, src/PhpPact/Consumer/Driver/InteractionPart/AbstractInteractionPartDriver.php, src/PhpPact/Consumer/Driver/InteractionPart/RequestDriver.php, src/PhpPact/Consumer/Driver/InteractionPart/ResponseDriver.php, src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, src/PhpPact/Plugin/Driver/Body/PluginBodyDriver.php, tests/PhpPact/Consumer/Driver/Interaction/MessageDriverTest.php, tests/PhpPact/Consumer/Driver/InteractionPart/RequestDriverTest.php, tests/PhpPact/Consumer/Driver/InteractionPart/ResponseDriverTest.php, tests/PhpPact/FFI/ClientTest.php, tests/PhpPact/Plugin/Driver/Body/PluginBodyDriverTest.php
Related to #644
Depend on #660
=> Wrap ffi call remaining methods

helper/FFI/ClientTrait.php, src/PhpPact/FFI/Client.php, src/PhpPact/FFI/ClientInterface.php, tests/PhpPact/FFI/ClientTest.php, tests/PhpPact/Plugin/Driver/Body/PluginBodyDriverTest.php
Related to #644
Depends on #661
=> Ffi client hide call method

example/generators/consumer/tests/Service/GeneratorsTest.php, example/generators/pacts/generatorsConsumer-generatorsProvider.json, example/generators/provider/public/index.php
=> chore: Add semver generator example

.github/workflows/compatibility-suite.yml
Show all logs from Pact FFI library for compatibility suite to debug random issue like #687
=> chore(compatibility-suite): Show log

docs/troubleshooting.md
The issues are:
* #692
* #727
* #703
=> docs: Add common issues related to loadding ffi to troubleshooting document
